import { Challenge } from "@/types/challenge";
import { EMPLOYEES_SEED, ECOMMERCE_SEED } from "../seed-data";

export const whereChallenges: Challenge[] = [
  {
    id: "where-01",
    title: "Simple Filter",
    description: "Select all employees from the **Engineering** department (department_id = 1). Return all columns.",
    category: "where",
    difficulty: "beginner",
    seedSQL: EMPLOYEES_SEED,
    expectedColumns: ["id", "first_name", "last_name", "email", "department_id", "salary", "hire_date", "manager_id"],
    expectedOutput: [
      [1, "Alice", "Johnson", "alice@company.com", 1, 95000, "2020-03-15", null],
      [2, "Bob", "Smith", "bob@company.com", 1, 88000, "2021-06-01", 1],
      [5, "Eva", "Davis", "eva@company.com", 1, 105000, "2018-07-22", null],
      [10, "Jack", "Anderson", "jack@company.com", 1, 92000, "2020-08-30", 5],
      [15, "Olivia", "Martin", null, 1, 78000, "2022-11-25", 1],
    ],
    hints: [
      "Use a WHERE clause to filter rows",
      "The Engineering department has department_id = 1",
      "SELECT * FROM employees WHERE department_id = 1",
    ],
    orderMatters: false,
    starterCode: "SELECT * FROM employees\n-- Add your WHERE clause here",
  },
  {
    id: "where-02",
    title: "Multiple Conditions (AND)",
    description: "Find employees who earn more than **$80,000** AND were hired after **2020-01-01**. Return their first_name, last_name, salary, and hire_date.",
    category: "where",
    difficulty: "beginner",
    seedSQL: EMPLOYEES_SEED,
    expectedColumns: ["first_name", "last_name", "salary", "hire_date"],
    expectedOutput: [
      ["Alice", "Johnson", 95000, "2020-03-15"],
      ["Bob", "Smith", 88000, "2021-06-01"],
      ["Jack", "Anderson", 92000, "2020-08-30"],
      ["Mia", "White", 91000, "2020-01-20"],
      ["Iris", "Taylor", 85000, "2019-04-18"],
    ],
    hints: [
      "Use AND to combine multiple conditions",
      "Compare salary > 80000 AND hire_date > '2020-01-01'",
      "SELECT first_name, last_name, salary, hire_date FROM employees WHERE salary > 80000 AND hire_date > '2020-01-01'",
    ],
    orderMatters: false,
  },
  {
    id: "where-03",
    title: "OR Conditions",
    description: "Find employees who are in the **Marketing** department (id=2) OR the **HR** department (id=4). Return first_name, last_name, and department_id.",
    category: "where",
    difficulty: "beginner",
    seedSQL: EMPLOYEES_SEED,
    expectedColumns: ["first_name", "last_name", "department_id"],
    expectedOutput: [
      ["Carol", "Williams", 2],
      ["Frank", "Miller", 2],
      ["Leo", "Jackson", 2],
      ["Henry", "Moore", 4],
      ["Noah", "Harris", 4],
    ],
    hints: [
      "Use OR to match either condition",
      "department_id = 2 OR department_id = 4",
      "SELECT first_name, last_name, department_id FROM employees WHERE department_id = 2 OR department_id = 4",
    ],
    orderMatters: false,
  },
  {
    id: "where-04",
    title: "LIKE Pattern Matching",
    description: "Find all employees whose **last name** starts with the letter 'M'. Return first_name and last_name.",
    category: "where",
    difficulty: "beginner",
    seedSQL: EMPLOYEES_SEED,
    expectedColumns: ["first_name", "last_name"],
    expectedOutput: [
      ["Frank", "Miller"],
      ["Henry", "Moore"],
      ["Olivia", "Martin"],
    ],
    hints: [
      "Use LIKE with a wildcard pattern",
      "The % wildcard matches any sequence of characters",
      "SELECT first_name, last_name FROM employees WHERE last_name LIKE 'M%'",
    ],
    orderMatters: false,
  },
  {
    id: "where-05",
    title: "IN Operator",
    description: "Find products in the **Electronics** category with a price that is exactly **$29.99**, **$49.99**, or **$89.99**. Return name and price.",
    category: "where",
    difficulty: "beginner",
    seedSQL: ECOMMERCE_SEED,
    expectedColumns: ["name", "price"],
    expectedOutput: [
      ["Wireless Mouse", 29.99],
      ["USB-C Hub", 49.99],
      ["Mechanical Keyboard", 89.99],
    ],
    hints: [
      "Use the IN operator for a list of values",
      "Combine category filter with IN for price",
      "SELECT name, price FROM products WHERE category = 'Electronics' AND price IN (29.99, 49.99, 89.99)",
    ],
    orderMatters: false,
  },
  {
    id: "where-06",
    title: "BETWEEN Range",
    description: "Find employees with a salary **between $70,000 and $90,000** (inclusive). Return first_name, last_name, and salary, ordered by salary descending.",
    category: "where",
    difficulty: "beginner",
    seedSQL: EMPLOYEES_SEED,
    expectedColumns: ["first_name", "last_name", "salary"],
    expectedOutput: [
      ["Bob", "Smith", 88000],
      ["Iris", "Taylor", 85000],
      ["Grace", "Wilson", 78000],
      ["Olivia", "Martin", 78000],
      ["Carol", "Williams", 72000],
      ["Karen", "Thomas", 71000],
    ],
    hints: [
      "Use BETWEEN for range filtering",
      "BETWEEN is inclusive on both ends",
      "SELECT first_name, last_name, salary FROM employees WHERE salary BETWEEN 70000 AND 90000 ORDER BY salary DESC",
    ],
    orderMatters: true,
  },
  {
    id: "where-07",
    title: "NULL Handling",
    description: "Find all employees who do **not** have a manager (manager_id is NULL). Return first_name, last_name, and department_id.",
    category: "where",
    difficulty: "beginner",
    seedSQL: EMPLOYEES_SEED,
    expectedColumns: ["first_name", "last_name", "department_id"],
    expectedOutput: [
      ["Alice", "Johnson", 1],
      ["Carol", "Williams", 2],
      ["David", "Brown", 3],
      ["Eva", "Davis", 1],
      ["Henry", "Moore", 4],
      ["Iris", "Taylor", 5],
    ],
    hints: [
      "You cannot use = NULL, you must use IS NULL",
      "WHERE manager_id IS NULL",
      "SELECT first_name, last_name, department_id FROM employees WHERE manager_id IS NULL",
    ],
    orderMatters: false,
  },
  {
    id: "where-08",
    title: "NOT and Complex Conditions",
    description: "Find orders that are **not** completed and have a total greater than **$100**. Return order id, status, and total.",
    category: "where",
    difficulty: "beginner",
    seedSQL: ECOMMERCE_SEED,
    expectedColumns: ["id", "status", "total"],
    expectedOutput: [
      [5, "shipped", 1299.99],
      [8, "pending", 449.99],
      [10, "shipped", 1749.98],
    ],
    hints: [
      "Use != or <> to check for not equal",
      "Combine with AND for the total check",
      "SELECT id, status, total FROM orders WHERE status != 'completed' AND total > 100",
    ],
    orderMatters: false,
  },
];
