import { Challenge } from "@/types/challenge";
import { EMPLOYEES_SEED } from "../seed-data";

export const advancedChallenges: Challenge[] = [
  {
    id: "adv-01",
    title: "Reusable CTE: High Earners",
    description:
      "Using a CTE named `high_earners` containing employees with salary **greater than 85000**, return a **single row** with two columns: `high_count` (the number of high earners) and `high_avg` (the average of their salaries, rounded to 2 decimals).",
    category: "advanced",
    difficulty: "advanced",
    seedSQL: EMPLOYEES_SEED,
    expectedColumns: ["high_count", "high_avg"],
    expectedOutput: [[5, 94200]],
    hints: [
      "Define the CTE with WITH high_earners AS (SELECT ... FROM employees WHERE salary > 85000).",
      "In the main query, use two scalar subqueries against high_earners to get the count and the rounded average.",
      "WITH high_earners AS (SELECT * FROM employees WHERE salary > 85000) SELECT (SELECT COUNT(*) FROM high_earners) AS high_count, (SELECT ROUND(AVG(salary), 2) FROM high_earners) AS high_avg",
    ],
    orderMatters: false,
    starterCode:
      "WITH high_earners AS (\n  SELECT * FROM employees WHERE salary > 85000\n)\nSELECT\n  -- count of high earners\n  ... AS high_count,\n  -- rounded average salary\n  ... AS high_avg;",
  },
  {
    id: "adv-02",
    title: "Recursive CTE: Org Chart Depth",
    description:
      "Using a **recursive CTE**, return every employee's id, first_name, and their management depth (1 = top-level with no manager, 2 = reports to a top-level, etc). Order by depth ascending, then first_name ascending.",
    category: "advanced",
    difficulty: "expert",
    seedSQL: EMPLOYEES_SEED,
    expectedColumns: ["id", "first_name", "depth"],
    expectedOutput: [
      [1, "Alice", 1],
      [3, "Carol", 1],
      [4, "David", 1],
      [5, "Eva", 1],
      [8, "Henry", 1],
      [9, "Iris", 1],
      [2, "Bob", 2],
      [6, "Frank", 2],
      [7, "Grace", 2],
      [10, "Jack", 2],
      [11, "Karen", 2],
      [12, "Leo", 2],
      [13, "Mia", 2],
      [14, "Noah", 2],
      [15, "Olivia", 2],
    ],
    hints: [
      "A recursive CTE has two parts joined by UNION ALL: the base case, then the recursive step.",
      "Base case: employees with manager_id IS NULL, depth = 1. Recursive step: join employees to the CTE on manager = id, depth + 1.",
      "WITH RECURSIVE org AS (SELECT id, first_name, 1 AS depth FROM employees WHERE manager_id IS NULL UNION ALL SELECT e.id, e.first_name, o.depth + 1 FROM employees e JOIN org o ON e.manager_id = o.id) SELECT id, first_name, depth FROM org ORDER BY depth, first_name",
    ],
    orderMatters: true,
  },
  {
    id: "adv-03",
    title: "Salary Bands with CASE",
    description:
      "Bucket employees into three bands using `CASE`: **Low** (salary < 70000), **Mid** (70000 – 89999), **High** (>= 90000). Return `band` and `cnt` (count of employees in each band). Order by band alphabetically.",
    category: "advanced",
    difficulty: "intermediate",
    seedSQL: EMPLOYEES_SEED,
    expectedColumns: ["band", "cnt"],
    expectedOutput: [
      ["High", 4],
      ["Low", 5],
      ["Mid", 6],
    ],
    hints: [
      "A CASE expression evaluates conditions top-to-bottom and returns the first match.",
      "You can GROUP BY the computed CASE column using its alias.",
      "SELECT CASE WHEN salary < 70000 THEN 'Low' WHEN salary < 90000 THEN 'Mid' ELSE 'High' END AS band, COUNT(*) AS cnt FROM employees GROUP BY band ORDER BY band",
    ],
    orderMatters: true,
  },
  {
    id: "adv-04",
    title: "Friendly Labels with COALESCE",
    description:
      "For each employee return first_name, a `manager_label` column, and an `email_display` column. For manager_label, show `'Manager #' || manager_id` when a manager exists, otherwise `'No manager'`. For email_display, show the email if present, otherwise `'no email'`. Order by first_name ascending.",
    category: "advanced",
    difficulty: "intermediate",
    seedSQL: EMPLOYEES_SEED,
    expectedColumns: ["first_name", "manager_label", "email_display"],
    expectedOutput: [
      ["Alice", "No manager", "alice@company.com"],
      ["Bob", "Manager #1", "bob@company.com"],
      ["Carol", "No manager", "carol@company.com"],
      ["David", "No manager", "david@company.com"],
      ["Eva", "No manager", "eva@company.com"],
      ["Frank", "Manager #3", "frank@company.com"],
      ["Grace", "Manager #4", "grace@company.com"],
      ["Henry", "No manager", "henry@company.com"],
      ["Iris", "No manager", "iris@company.com"],
      ["Jack", "Manager #5", "jack@company.com"],
      ["Karen", "Manager #4", "karen@company.com"],
      ["Leo", "Manager #3", "leo@company.com"],
      ["Mia", "Manager #9", "mia@company.com"],
      ["Noah", "Manager #8", "noah@company.com"],
      ["Olivia", "Manager #1", "no email"],
    ],
    hints: [
      "COALESCE(a, b) returns a if not NULL, otherwise b.",
      "Concatenation with NULL yields NULL in SQL: 'Manager #' || NULL = NULL, which COALESCE can then replace.",
      "SELECT first_name, COALESCE('Manager #' || manager_id, 'No manager') AS manager_label, COALESCE(email, 'no email') AS email_display FROM employees ORDER BY first_name",
    ],
    orderMatters: true,
  },
  {
    id: "adv-05",
    title: "UNION with Extra People",
    description:
      "Combine employee first_names with three contractor names - **'Rita'**, **'Sam'**, and **'Tara'** - into a single column called `person_name`, deduplicated, sorted alphabetically. Use `UNION`.",
    category: "advanced",
    difficulty: "intermediate",
    seedSQL: EMPLOYEES_SEED,
    expectedColumns: ["person_name"],
    expectedOutput: [
      ["Alice"],
      ["Bob"],
      ["Carol"],
      ["David"],
      ["Eva"],
      ["Frank"],
      ["Grace"],
      ["Henry"],
      ["Iris"],
      ["Jack"],
      ["Karen"],
      ["Leo"],
      ["Mia"],
      ["Noah"],
      ["Olivia"],
      ["Rita"],
      ["Sam"],
      ["Tara"],
    ],
    hints: [
      "UNION combines the result sets of two SELECTs and removes duplicates. UNION ALL keeps duplicates.",
      "You can SELECT a literal value like SELECT 'Rita' - no FROM clause needed.",
      "SELECT first_name AS person_name FROM employees UNION SELECT 'Rita' UNION SELECT 'Sam' UNION SELECT 'Tara' ORDER BY person_name",
    ],
    orderMatters: true,
  },
  {
    id: "adv-06",
    title: "Top Earner per Department (CTE + Window + JOIN)",
    description:
      "Using a CTE that uses `DENSE_RANK() OVER (PARTITION BY ...)` to rank employees within their department by salary descending, return only the **top-ranked employee per department**. Return first_name, department_name, salary, and dept_rank. Order by department_name ascending.",
    category: "advanced",
    difficulty: "expert",
    seedSQL: EMPLOYEES_SEED,
    expectedColumns: ["first_name", "department_name", "salary", "dept_rank"],
    expectedOutput: [
      ["Eva", "Engineering", 105000, 1],
      ["Mia", "Finance", 91000, 1],
      ["Henry", "HR", 62000, 1],
      ["Carol", "Marketing", 72000, 1],
      ["Grace", "Sales", 78000, 1],
    ],
    hints: [
      "Compose three features: JOIN employees to departments, compute DENSE_RANK partitioned by department, then filter where rank = 1.",
      "Put the ranking inside a CTE so the final SELECT can filter on the computed rank column (window functions can't be referenced in a WHERE clause directly).",
      "WITH ranked AS (SELECT e.first_name, e.salary, d.name AS department_name, DENSE_RANK() OVER (PARTITION BY e.department_id ORDER BY e.salary DESC) AS dept_rank FROM employees e JOIN departments d ON e.department_id = d.id) SELECT first_name, department_name, salary, dept_rank FROM ranked WHERE dept_rank = 1 ORDER BY department_name",
    ],
    orderMatters: true,
  },
];
