import { Challenge } from "@/types/challenge";
import { EMPLOYEES_SEED, ECOMMERCE_SEED } from "../seed-data";

export const aggregationChallenges: Challenge[] = [
  {
    id: "agg-01",
    title: "COUNT Basics",
    description: "Count the **total number of employees**. Return a single column called total_employees.",
    category: "aggregation",
    difficulty: "beginner",
    seedSQL: EMPLOYEES_SEED,
    expectedColumns: ["total_employees"],
    expectedOutput: [[15]],
    hints: [
      "Use the COUNT() function",
      "COUNT(*) counts all rows",
      "SELECT COUNT(*) AS total_employees FROM employees",
    ],
    orderMatters: false,
  },
  {
    id: "agg-02",
    title: "SUM and AVG",
    description: "Calculate the **total salary** and **average salary** across all employees. Return total_salary and avg_salary (rounded to 2 decimal places).",
    category: "aggregation",
    difficulty: "beginner",
    seedSQL: EMPLOYEES_SEED,
    expectedColumns: ["total_salary", "avg_salary"],
    expectedOutput: [[1177000, 78466.67]],
    hints: [
      "Use SUM() and AVG() aggregate functions",
      "Use ROUND() to round to 2 decimal places",
      "SELECT SUM(salary) AS total_salary, ROUND(AVG(salary), 2) AS avg_salary FROM employees",
    ],
    orderMatters: false,
  },
  {
    id: "agg-03",
    title: "GROUP BY",
    description: "Show the **average salary per department**. Return department_id and avg_salary (rounded to 2 decimal places), ordered by avg_salary descending.",
    category: "aggregation",
    difficulty: "beginner",
    seedSQL: EMPLOYEES_SEED,
    expectedColumns: ["department_id", "avg_salary"],
    expectedOutput: [
      [1, 91600.0],
      [5, 88000.0],
      [3, 72333.33],
      [2, 68666.67],
      [4, 60000.0],
    ],
    hints: [
      "Use GROUP BY to group rows by department_id",
      "Apply AVG() to the salary column within each group",
      "SELECT department_id, ROUND(AVG(salary), 2) AS avg_salary FROM employees GROUP BY department_id ORDER BY avg_salary DESC",
    ],
    orderMatters: true,
  },
  {
    id: "agg-04",
    title: "HAVING Clause",
    description: "Find departments that have **more than 2 employees**. Return department_id and employee_count.",
    category: "aggregation",
    difficulty: "intermediate",
    seedSQL: EMPLOYEES_SEED,
    expectedColumns: ["department_id", "employee_count"],
    expectedOutput: [
      [1, 5],
      [2, 3],
      [3, 3],
    ],
    hints: [
      "Use GROUP BY then HAVING to filter groups",
      "HAVING is like WHERE but for aggregated results",
      "SELECT department_id, COUNT(*) AS employee_count FROM employees GROUP BY department_id HAVING COUNT(*) > 2",
    ],
    orderMatters: false,
  },
  {
    id: "agg-05",
    title: "MIN and MAX",
    description: "For each product category, find the **cheapest** and **most expensive** product price. Return category, min_price, and max_price.",
    category: "aggregation",
    difficulty: "beginner",
    seedSQL: ECOMMERCE_SEED,
    expectedColumns: ["category", "min_price", "max_price"],
    expectedOutput: [
      ["Electronics", 29.99, 1299.99],
      ["Office", 12.99, 599.99],
    ],
    hints: [
      "Use MIN() and MAX() with GROUP BY",
      "Group by the category column",
      "SELECT category, MIN(price) AS min_price, MAX(price) AS max_price FROM products GROUP BY category",
    ],
    orderMatters: false,
  },
  {
    id: "agg-06",
    title: "COUNT with DISTINCT",
    description: "Count the number of **unique cities** our customers come from. Return a column called unique_cities.",
    category: "aggregation",
    difficulty: "beginner",
    seedSQL: ECOMMERCE_SEED,
    expectedColumns: ["unique_cities"],
    expectedOutput: [[8]],
    hints: [
      "Use COUNT(DISTINCT column) to count unique values",
      "Count distinct values in the city column",
      "SELECT COUNT(DISTINCT city) AS unique_cities FROM customers",
    ],
    orderMatters: false,
  },
  {
    id: "agg-07",
    title: "Aggregation with JOIN",
    description: "Show each customer's name and their **total spending** (sum of order totals). Only include customers who have spent more than **$500**. Return name and total_spent, ordered by total_spent descending.",
    category: "aggregation",
    difficulty: "intermediate",
    seedSQL: ECOMMERCE_SEED,
    expectedColumns: ["name", "total_spent"],
    expectedOutput: [
      ["Sofia Rossi", 1749.98],
      ["John Doe", 1519.95],
      ["Yuki Tanaka", 699.98],
      ["Jane Smith", 939.97],
    ],
    hints: [
      "JOIN customers with orders, then GROUP BY customer",
      "Use SUM(total) and HAVING to filter",
      "SELECT c.name, SUM(o.total) AS total_spent FROM customers c JOIN orders o ON c.id = o.customer_id GROUP BY c.name HAVING SUM(o.total) > 500 ORDER BY total_spent DESC",
    ],
    orderMatters: true,
  },
];
