export type KeywordCategory =
  | "dml" // Data manipulation
  | "ddl" // Data definition
  | "dcl" // Data control (permissions)
  | "tcl" // Transaction control
  | "clause" // Statement clause
  | "operator" // Logical / comparison / set operators
  | "datatype" // Types
  | "function" // Built-in functions
  | "constraint" // Column / table constraints
  | "join" // Join kinds
  | "literal" // Keyword literals (NULL, TRUE, ...)
  | "meta"; // EXPLAIN, PRAGMA, ...

export type ReservedStatus = "reserved" | "non-reserved" | "mixed";

export interface KeywordEntry {
  /** Canonical keyword (uppercase). */
  keyword: string;
  category: KeywordCategory;
  reserved: ReservedStatus;
  /** Engines that implement this keyword. */
  engines: ("standard" | "sqlite" | "postgres" | "mysql" | "oracle" | "mssql")[];
  /** Short description - one sentence. */
  summary: string;
  /** Minimal syntax hint. */
  syntax?: string;
  /** A small runnable example. */
  example?: string;
  /** Related keywords to cross-link. */
  related?: string[];
  /** Optional longer note - edge cases, portability, etc. */
  notes?: string;
}

export const CATEGORY_LABEL: Record<KeywordCategory, string> = {
  dml: "Data manipulation",
  ddl: "Data definition",
  dcl: "Data control",
  tcl: "Transactions",
  clause: "Clauses",
  operator: "Operators",
  datatype: "Data types",
  function: "Functions",
  constraint: "Constraints",
  join: "Joins",
  literal: "Literals",
  meta: "Meta / tooling",
};

export const CATEGORY_DESCRIPTION: Record<KeywordCategory, string> = {
  dml: "Statements that read or change rows - SELECT, INSERT, UPDATE, DELETE, MERGE.",
  ddl: "Statements that define schema - CREATE, ALTER, DROP, TRUNCATE.",
  dcl: "Permissions - GRANT and REVOKE.",
  tcl: "Transaction boundaries - BEGIN, COMMIT, ROLLBACK, SAVEPOINT.",
  clause: "Building blocks that compose inside statements - WHERE, GROUP BY, HAVING, ...",
  operator: "Logical, comparison, and set operators.",
  datatype: "Column type names - INTEGER, TEXT, NUMERIC, etc.",
  function: "Built-in functions - aggregates, string, date, conditional.",
  constraint: "Rules attached to columns or tables - PRIMARY KEY, NOT NULL, CHECK, ...",
  join: "The join family.",
  literal: "Keyword literals that represent values.",
  meta: "Tools for inspecting or tuning - EXPLAIN, PRAGMA, SHOW, VACUUM.",
};

export const SQL_KEYWORDS: KeywordEntry[] = [
  // -------------------------------------------------------------------------
  // DML
  // -------------------------------------------------------------------------
  {
    keyword: "SELECT",
    category: "dml",
    reserved: "reserved",
    engines: ["standard", "sqlite", "postgres", "mysql", "oracle", "mssql"],
    summary: "Retrieve rows from one or more tables.",
    syntax: "SELECT column_list FROM table [WHERE ...] [GROUP BY ...] [ORDER BY ...];",
    example: "SELECT id, name FROM users WHERE active = 1;",
    related: ["FROM", "WHERE", "JOIN", "ORDER BY"],
  },
  {
    keyword: "INSERT",
    category: "dml",
    reserved: "reserved",
    engines: ["standard", "sqlite", "postgres", "mysql", "oracle", "mssql"],
    summary: "Add new rows to a table.",
    syntax: "INSERT INTO table (col, ...) VALUES (val, ...);",
    example: "INSERT INTO users (name, email) VALUES ('Alice', 'a@a.com');",
    related: ["VALUES", "INTO", "ON CONFLICT"],
  },
  {
    keyword: "UPDATE",
    category: "dml",
    reserved: "reserved",
    engines: ["standard", "sqlite", "postgres", "mysql", "oracle", "mssql"],
    summary: "Modify existing rows in a table.",
    syntax: "UPDATE table SET col = value [WHERE ...];",
    example: "UPDATE users SET active = 0 WHERE last_login < '2020-01-01';",
    notes: "Always include a WHERE clause - an UPDATE without one rewrites every row.",
    related: ["SET", "WHERE"],
  },
  {
    keyword: "DELETE",
    category: "dml",
    reserved: "reserved",
    engines: ["standard", "sqlite", "postgres", "mysql", "oracle", "mssql"],
    summary: "Remove rows from a table.",
    syntax: "DELETE FROM table [WHERE ...];",
    example: "DELETE FROM sessions WHERE expires_at < CURRENT_TIMESTAMP;",
    related: ["FROM", "WHERE", "TRUNCATE"],
  },
  {
    keyword: "MERGE",
    category: "dml",
    reserved: "reserved",
    engines: ["standard", "postgres", "oracle", "mssql"],
    summary: "Insert, update, or delete in one statement based on a match condition.",
    syntax: "MERGE INTO target USING source ON cond WHEN MATCHED THEN UPDATE ... WHEN NOT MATCHED THEN INSERT ...;",
    notes: "SQLite and MySQL don't support MERGE; use INSERT ... ON CONFLICT / ON DUPLICATE KEY.",
    related: ["ON CONFLICT", "UPSERT"],
  },
  {
    keyword: "UPSERT",
    category: "dml",
    reserved: "non-reserved",
    engines: ["sqlite"],
    summary: "Shorthand for INSERT ... ON CONFLICT DO UPDATE (SQLite specific).",
    syntax: "INSERT INTO t(...) VALUES(...) ON CONFLICT(col) DO UPDATE SET ...;",
    related: ["ON CONFLICT", "INSERT"],
  },
  {
    keyword: "RETURNING",
    category: "clause",
    reserved: "non-reserved",
    engines: ["standard", "sqlite", "postgres"],
    summary: "Return columns from rows affected by INSERT/UPDATE/DELETE.",
    syntax: "INSERT INTO t(...) VALUES(...) RETURNING id;",
    example: "DELETE FROM sessions WHERE id = 1 RETURNING user_id;",
  },

  // -------------------------------------------------------------------------
  // Clauses / projection
  // -------------------------------------------------------------------------
  {
    keyword: "FROM",
    category: "clause",
    reserved: "reserved",
    engines: ["standard", "sqlite", "postgres", "mysql", "oracle", "mssql"],
    summary: "Specifies the tables (or subqueries) a SELECT/DELETE reads from.",
    syntax: "SELECT ... FROM table_or_subquery [AS alias];",
  },
  {
    keyword: "WHERE",
    category: "clause",
    reserved: "reserved",
    engines: ["standard", "sqlite", "postgres", "mysql", "oracle", "mssql"],
    summary: "Filters rows based on a boolean condition.",
    syntax: "WHERE condition",
    example: "SELECT * FROM orders WHERE amount > 100;",
  },
  {
    keyword: "GROUP BY",
    category: "clause",
    reserved: "reserved",
    engines: ["standard", "sqlite", "postgres", "mysql", "oracle", "mssql"],
    summary: "Collapses rows into one row per distinct value of the grouped columns.",
    syntax: "GROUP BY column_list",
    example: "SELECT city, COUNT(*) FROM users GROUP BY city;",
    related: ["HAVING", "COUNT", "SUM"],
  },
  {
    keyword: "HAVING",
    category: "clause",
    reserved: "reserved",
    engines: ["standard", "sqlite", "postgres", "mysql", "oracle", "mssql"],
    summary: "Filters groups after aggregation.",
    syntax: "HAVING aggregate_condition",
    example: "SELECT city, COUNT(*) FROM users GROUP BY city HAVING COUNT(*) > 10;",
  },
  {
    keyword: "ORDER BY",
    category: "clause",
    reserved: "reserved",
    engines: ["standard", "sqlite", "postgres", "mysql", "oracle", "mssql"],
    summary: "Sorts rows in the result by one or more columns or expressions.",
    syntax: "ORDER BY col [ASC|DESC] [, ...]",
  },
  {
    keyword: "LIMIT",
    category: "clause",
    reserved: "non-reserved",
    engines: ["sqlite", "postgres", "mysql"],
    summary: "Restricts how many rows are returned.",
    syntax: "LIMIT n [OFFSET k]",
    notes: "SQL Server / Oracle use OFFSET ... FETCH NEXT instead.",
  },
  {
    keyword: "OFFSET",
    category: "clause",
    reserved: "non-reserved",
    engines: ["standard", "sqlite", "postgres", "mysql"],
    summary: "Skip this many rows before returning results.",
    syntax: "OFFSET k",
  },
  {
    keyword: "FETCH",
    category: "clause",
    reserved: "reserved",
    engines: ["standard", "postgres", "oracle", "mssql"],
    summary: "Standard alternative to LIMIT: `FETCH NEXT n ROWS ONLY`.",
  },
  {
    keyword: "DISTINCT",
    category: "clause",
    reserved: "reserved",
    engines: ["standard", "sqlite", "postgres", "mysql", "oracle", "mssql"],
    summary: "Removes duplicate rows from the result.",
    syntax: "SELECT DISTINCT col_list FROM ...",
    example: "SELECT DISTINCT city FROM users;",
  },
  {
    keyword: "ALL",
    category: "clause",
    reserved: "reserved",
    engines: ["standard", "sqlite", "postgres", "mysql", "oracle"],
    summary: "Opposite of DISTINCT - keeps duplicates. Also used in UNION ALL and as quantifier.",
    syntax: "SELECT ALL ...   |   UNION ALL   |   expr > ALL (subquery)",
  },
  {
    keyword: "AS",
    category: "clause",
    reserved: "reserved",
    engines: ["standard", "sqlite", "postgres", "mysql", "oracle", "mssql"],
    summary: "Rename a column or table with an alias.",
    syntax: "expression AS alias",
    example: "SELECT first_name AS name FROM users;",
  },
  {
    keyword: "WITH",
    category: "clause",
    reserved: "reserved",
    engines: ["standard", "sqlite", "postgres", "mysql", "oracle", "mssql"],
    summary: "Declares one or more CTEs (named intermediate result sets) for the following query.",
    syntax: "WITH name AS (subquery) [, ...] SELECT ...",
  },
  {
    keyword: "RECURSIVE",
    category: "clause",
    reserved: "non-reserved",
    engines: ["standard", "sqlite", "postgres"],
    summary: "Marks a WITH-CTE as recursive so it can reference itself.",
    syntax: "WITH RECURSIVE name AS (...) SELECT ...",
  },
  {
    keyword: "OVER",
    category: "clause",
    reserved: "reserved",
    engines: ["standard", "sqlite", "postgres", "mysql", "oracle", "mssql"],
    summary: "Defines the window for a window function.",
    syntax: "function() OVER (PARTITION BY ... ORDER BY ... [frame])",
  },
  {
    keyword: "PARTITION BY",
    category: "clause",
    reserved: "reserved",
    engines: ["standard", "sqlite", "postgres", "mysql", "oracle", "mssql"],
    summary: "Divides a window into groups; each group is handled independently.",
    syntax: "OVER (PARTITION BY col [, ...])",
  },
  {
    keyword: "WINDOW",
    category: "clause",
    reserved: "reserved",
    engines: ["standard", "sqlite", "postgres"],
    summary: "Names a window spec so multiple window functions can reuse it.",
    syntax: "SELECT ... FROM t WINDOW w AS (PARTITION BY col ORDER BY col)",
  },
  {
    keyword: "VALUES",
    category: "clause",
    reserved: "reserved",
    engines: ["standard", "sqlite", "postgres", "mysql"],
    summary: "Inline row literals. Used in INSERT and as a standalone table constructor.",
    example: "SELECT * FROM (VALUES (1,'a'),(2,'b')) AS t(id, label);",
  },
  {
    keyword: "SET",
    category: "clause",
    reserved: "reserved",
    engines: ["standard", "sqlite", "postgres", "mysql", "oracle", "mssql"],
    summary: "Names the columns and new values in UPDATE.",
    syntax: "UPDATE t SET col = value [, ...]",
  },
  {
    keyword: "INTO",
    category: "clause",
    reserved: "reserved",
    engines: ["standard", "sqlite", "postgres", "mysql", "oracle", "mssql"],
    summary: "Target of INSERT; also used in SELECT ... INTO (MSSQL) to materialize a new table.",
  },
  {
    keyword: "ON",
    category: "clause",
    reserved: "reserved",
    engines: ["standard", "sqlite", "postgres", "mysql", "oracle", "mssql"],
    summary: "Join condition - specifies how two tables are matched in JOIN.",
    syntax: "JOIN other ON condition",
  },
  {
    keyword: "USING",
    category: "clause",
    reserved: "reserved",
    engines: ["standard", "sqlite", "postgres", "mysql", "oracle"],
    summary: "Shorthand join condition when both tables share a column name.",
    syntax: "a JOIN b USING (shared_col)",
  },
  {
    keyword: "ON CONFLICT",
    category: "clause",
    reserved: "non-reserved",
    engines: ["sqlite", "postgres"],
    summary: "Upsert clause - react to a unique constraint violation.",
    syntax: "INSERT ... ON CONFLICT(col) DO { UPDATE SET ... | NOTHING }",
    example: "INSERT INTO t(id,name) VALUES(1,'a') ON CONFLICT(id) DO UPDATE SET name=excluded.name;",
  },
  {
    keyword: "DO NOTHING",
    category: "clause",
    reserved: "non-reserved",
    engines: ["sqlite", "postgres"],
    summary: "Ignore the conflict and skip the row.",
  },
  {
    keyword: "DO UPDATE",
    category: "clause",
    reserved: "non-reserved",
    engines: ["sqlite", "postgres"],
    summary: "Resolve conflict by updating the existing row.",
  },

  // -------------------------------------------------------------------------
  // Joins
  // -------------------------------------------------------------------------
  {
    keyword: "JOIN",
    category: "join",
    reserved: "reserved",
    engines: ["standard", "sqlite", "postgres", "mysql", "oracle", "mssql"],
    summary: "Combine rows from two tables matching a condition (defaults to INNER).",
    syntax: "FROM a JOIN b ON a.id = b.a_id",
  },
  {
    keyword: "INNER JOIN",
    category: "join",
    reserved: "reserved",
    engines: ["standard", "sqlite", "postgres", "mysql", "oracle", "mssql"],
    summary: "Rows that match on both sides; unmatched rows are dropped.",
  },
  {
    keyword: "LEFT JOIN",
    category: "join",
    reserved: "reserved",
    engines: ["standard", "sqlite", "postgres", "mysql", "oracle", "mssql"],
    summary: "All rows from the left, NULLs from the right when no match.",
  },
  {
    keyword: "RIGHT JOIN",
    category: "join",
    reserved: "reserved",
    engines: ["standard", "postgres", "mysql", "oracle", "mssql"],
    summary: "All rows from the right, NULLs from the left when no match.",
    notes: "SQLite added RIGHT JOIN in 3.39 (2022).",
  },
  {
    keyword: "FULL JOIN",
    category: "join",
    reserved: "reserved",
    engines: ["standard", "postgres", "oracle", "mssql"],
    summary: "All rows from both sides; NULLs where no match.",
    notes: "MySQL and older SQLite don't support FULL JOIN - emulate with LEFT UNION RIGHT.",
  },
  {
    keyword: "CROSS JOIN",
    category: "join",
    reserved: "reserved",
    engines: ["standard", "sqlite", "postgres", "mysql", "oracle", "mssql"],
    summary: "Cartesian product - every row of A paired with every row of B.",
  },
  {
    keyword: "NATURAL JOIN",
    category: "join",
    reserved: "reserved",
    engines: ["standard", "sqlite", "postgres", "mysql", "oracle"],
    summary: "Auto-joins tables on columns with the same name.",
    notes: "Rarely used in practice - explicit ON/USING is clearer and safer.",
  },
  {
    keyword: "LATERAL",
    category: "join",
    reserved: "reserved",
    engines: ["standard", "postgres", "mysql", "oracle"],
    summary: "Allows a subquery in FROM to reference columns from earlier tables in the same FROM.",
  },

  // -------------------------------------------------------------------------
  // Operators / predicates
  // -------------------------------------------------------------------------
  {
    keyword: "AND",
    category: "operator",
    reserved: "reserved",
    engines: ["standard", "sqlite", "postgres", "mysql", "oracle", "mssql"],
    summary: "Logical AND - both operands must be true.",
  },
  {
    keyword: "OR",
    category: "operator",
    reserved: "reserved",
    engines: ["standard", "sqlite", "postgres", "mysql", "oracle", "mssql"],
    summary: "Logical OR - either operand may be true.",
  },
  {
    keyword: "NOT",
    category: "operator",
    reserved: "reserved",
    engines: ["standard", "sqlite", "postgres", "mysql", "oracle", "mssql"],
    summary: "Logical negation.",
  },
  {
    keyword: "IN",
    category: "operator",
    reserved: "reserved",
    engines: ["standard", "sqlite", "postgres", "mysql", "oracle", "mssql"],
    summary: "Membership test - true when value appears in a list or subquery.",
    example: "WHERE status IN ('new', 'open', 'review')",
  },
  {
    keyword: "NOT IN",
    category: "operator",
    reserved: "reserved",
    engines: ["standard", "sqlite", "postgres", "mysql", "oracle", "mssql"],
    summary: "Inverse of IN. Watch out - a NULL in the list makes the whole predicate NULL.",
    notes: "For null-safe negation prefer NOT EXISTS.",
  },
  {
    keyword: "BETWEEN",
    category: "operator",
    reserved: "reserved",
    engines: ["standard", "sqlite", "postgres", "mysql", "oracle", "mssql"],
    summary: "Range predicate: `x BETWEEN a AND b` (both endpoints inclusive).",
  },
  {
    keyword: "LIKE",
    category: "operator",
    reserved: "reserved",
    engines: ["standard", "sqlite", "postgres", "mysql", "oracle", "mssql"],
    summary: "Pattern match with `%` and `_` wildcards.",
    example: "WHERE name LIKE 'A%'",
  },
  {
    keyword: "ILIKE",
    category: "operator",
    reserved: "non-reserved",
    engines: ["postgres"],
    summary: "Case-insensitive LIKE (Postgres).",
  },
  {
    keyword: "GLOB",
    category: "operator",
    reserved: "non-reserved",
    engines: ["sqlite"],
    summary: "Unix-style glob match (SQLite).",
  },
  {
    keyword: "IS",
    category: "operator",
    reserved: "reserved",
    engines: ["standard", "sqlite", "postgres", "mysql", "oracle", "mssql"],
    summary: "NULL-safe equality. Use with NULL / TRUE / FALSE / DISTINCT FROM.",
    example: "WHERE deleted_at IS NULL",
  },
  {
    keyword: "IS NULL",
    category: "operator",
    reserved: "reserved",
    engines: ["standard", "sqlite", "postgres", "mysql", "oracle", "mssql"],
    summary: "True when the value is NULL.",
  },
  {
    keyword: "IS NOT NULL",
    category: "operator",
    reserved: "reserved",
    engines: ["standard", "sqlite", "postgres", "mysql", "oracle", "mssql"],
    summary: "True when the value is not NULL.",
  },
  {
    keyword: "IS DISTINCT FROM",
    category: "operator",
    reserved: "reserved",
    engines: ["standard", "postgres", "sqlite"],
    summary: "NULL-safe not-equal: treats two NULLs as equal.",
  },
  {
    keyword: "EXISTS",
    category: "operator",
    reserved: "reserved",
    engines: ["standard", "sqlite", "postgres", "mysql", "oracle", "mssql"],
    summary: "True as soon as the subquery returns any row.",
  },
  {
    keyword: "ANY",
    category: "operator",
    reserved: "reserved",
    engines: ["standard", "postgres", "mysql", "oracle", "mssql"],
    summary: "True if the comparison holds for any value returned by the subquery.",
  },
  {
    keyword: "SOME",
    category: "operator",
    reserved: "reserved",
    engines: ["standard", "postgres", "oracle", "mssql"],
    summary: "Synonym for ANY.",
  },
  {
    keyword: "UNION",
    category: "operator",
    reserved: "reserved",
    engines: ["standard", "sqlite", "postgres", "mysql", "oracle", "mssql"],
    summary: "Combine two result sets and remove duplicates.",
  },
  {
    keyword: "UNION ALL",
    category: "operator",
    reserved: "reserved",
    engines: ["standard", "sqlite", "postgres", "mysql", "oracle", "mssql"],
    summary: "UNION that keeps duplicates - much faster than UNION.",
  },
  {
    keyword: "INTERSECT",
    category: "operator",
    reserved: "reserved",
    engines: ["standard", "sqlite", "postgres", "oracle", "mssql"],
    summary: "Rows that appear in both result sets.",
  },
  {
    keyword: "EXCEPT",
    category: "operator",
    reserved: "reserved",
    engines: ["standard", "sqlite", "postgres", "oracle", "mssql"],
    summary: "Rows in the first result but not the second.",
    notes: "MySQL calls this MINUS in some contexts; EXCEPT is the standard spelling.",
  },
  {
    keyword: "MINUS",
    category: "operator",
    reserved: "reserved",
    engines: ["oracle"],
    summary: "Oracle's spelling of EXCEPT.",
  },

  // -------------------------------------------------------------------------
  // DDL
  // -------------------------------------------------------------------------
  {
    keyword: "CREATE",
    category: "ddl",
    reserved: "reserved",
    engines: ["standard", "sqlite", "postgres", "mysql", "oracle", "mssql"],
    summary: "Create a table, index, view, trigger, schema, etc.",
    syntax: "CREATE { TABLE | INDEX | VIEW | TRIGGER | SCHEMA } name ...",
  },
  {
    keyword: "CREATE TABLE",
    category: "ddl",
    reserved: "reserved",
    engines: ["standard", "sqlite", "postgres", "mysql", "oracle", "mssql"],
    summary: "Create a new table with a column definition list.",
    example: "CREATE TABLE users (id INTEGER PRIMARY KEY, name TEXT);",
  },
  {
    keyword: "CREATE TEMPORARY TABLE",
    category: "ddl",
    reserved: "non-reserved",
    engines: ["standard", "sqlite", "postgres", "mysql", "oracle"],
    summary: "A table that is automatically dropped at the end of the session.",
  },
  {
    keyword: "CREATE INDEX",
    category: "ddl",
    reserved: "reserved",
    engines: ["standard", "sqlite", "postgres", "mysql", "oracle", "mssql"],
    summary: "Create a secondary index to speed up lookups.",
    example: "CREATE INDEX idx_users_email ON users(email);",
  },
  {
    keyword: "CREATE UNIQUE INDEX",
    category: "ddl",
    reserved: "reserved",
    engines: ["standard", "sqlite", "postgres", "mysql", "oracle", "mssql"],
    summary: "Index that also enforces uniqueness of the indexed columns.",
  },
  {
    keyword: "CREATE VIEW",
    category: "ddl",
    reserved: "reserved",
    engines: ["standard", "sqlite", "postgres", "mysql", "oracle", "mssql"],
    summary: "Save a query as a named view for reuse.",
    example: "CREATE VIEW active_users AS SELECT * FROM users WHERE active = 1;",
  },
  {
    keyword: "CREATE MATERIALIZED VIEW",
    category: "ddl",
    reserved: "non-reserved",
    engines: ["postgres", "oracle"],
    summary: "Like a view but physically stores the result for fast reads.",
  },
  {
    keyword: "CREATE TRIGGER",
    category: "ddl",
    reserved: "reserved",
    engines: ["standard", "sqlite", "postgres", "mysql", "oracle", "mssql"],
    summary: "Define code that runs before/after INSERT/UPDATE/DELETE.",
  },
  {
    keyword: "CREATE SCHEMA",
    category: "ddl",
    reserved: "reserved",
    engines: ["standard", "postgres", "mysql", "oracle", "mssql"],
    summary: "Create a namespace that groups tables/objects.",
  },
  {
    keyword: "CREATE FUNCTION",
    category: "ddl",
    reserved: "reserved",
    engines: ["standard", "postgres", "mysql", "oracle", "mssql"],
    summary: "Define a user function (PL/pgSQL, PL/SQL, T-SQL, etc.).",
  },
  {
    keyword: "CREATE PROCEDURE",
    category: "ddl",
    reserved: "reserved",
    engines: ["standard", "postgres", "mysql", "oracle", "mssql"],
    summary: "Define a stored procedure.",
  },
  {
    keyword: "ALTER",
    category: "ddl",
    reserved: "reserved",
    engines: ["standard", "sqlite", "postgres", "mysql", "oracle", "mssql"],
    summary: "Change an existing database object.",
    syntax: "ALTER TABLE name { ADD | DROP | RENAME | ALTER } COLUMN ...",
  },
  {
    keyword: "ALTER TABLE",
    category: "ddl",
    reserved: "reserved",
    engines: ["standard", "sqlite", "postgres", "mysql", "oracle", "mssql"],
    summary: "Modify a table - add/drop/rename columns, change constraints.",
    example: "ALTER TABLE users ADD COLUMN avatar_url TEXT;",
    notes: "SQLite supports a limited subset (rename column, add column, drop column since 3.35).",
  },
  {
    keyword: "RENAME",
    category: "ddl",
    reserved: "non-reserved",
    engines: ["standard", "sqlite", "postgres", "mysql", "oracle", "mssql"],
    summary: "Rename a table or column via ALTER TABLE.",
    example: "ALTER TABLE users RENAME TO accounts;",
  },
  {
    keyword: "DROP",
    category: "ddl",
    reserved: "reserved",
    engines: ["standard", "sqlite", "postgres", "mysql", "oracle", "mssql"],
    summary: "Remove a database object.",
    example: "DROP TABLE IF EXISTS temp_events;",
  },
  {
    keyword: "DROP TABLE",
    category: "ddl",
    reserved: "reserved",
    engines: ["standard", "sqlite", "postgres", "mysql", "oracle", "mssql"],
    summary: "Delete a table and all its data.",
  },
  {
    keyword: "DROP INDEX",
    category: "ddl",
    reserved: "reserved",
    engines: ["standard", "sqlite", "postgres", "mysql", "oracle", "mssql"],
    summary: "Remove an index.",
  },
  {
    keyword: "DROP VIEW",
    category: "ddl",
    reserved: "reserved",
    engines: ["standard", "sqlite", "postgres", "mysql", "oracle", "mssql"],
    summary: "Remove a view.",
  },
  {
    keyword: "TRUNCATE",
    category: "ddl",
    reserved: "reserved",
    engines: ["standard", "postgres", "mysql", "oracle", "mssql"],
    summary: "Delete all rows in a table efficiently - faster than DELETE, often unlogged.",
    notes: "SQLite doesn't have TRUNCATE; DELETE FROM t does an optimized truncate when there is no WHERE.",
  },
  {
    keyword: "IF EXISTS",
    category: "clause",
    reserved: "non-reserved",
    engines: ["standard", "sqlite", "postgres", "mysql"],
    summary: "Don't error if the object doesn't exist (DROP ... IF EXISTS).",
  },
  {
    keyword: "IF NOT EXISTS",
    category: "clause",
    reserved: "non-reserved",
    engines: ["standard", "sqlite", "postgres", "mysql"],
    summary: "Don't error if the object already exists (CREATE ... IF NOT EXISTS).",
  },

  // -------------------------------------------------------------------------
  // Constraints
  // -------------------------------------------------------------------------
  {
    keyword: "PRIMARY KEY",
    category: "constraint",
    reserved: "reserved",
    engines: ["standard", "sqlite", "postgres", "mysql", "oracle", "mssql"],
    summary: "Marks one or more columns as the table's unique identifier.",
    example: "CREATE TABLE t(id INTEGER PRIMARY KEY);",
  },
  {
    keyword: "FOREIGN KEY",
    category: "constraint",
    reserved: "reserved",
    engines: ["standard", "sqlite", "postgres", "mysql", "oracle", "mssql"],
    summary: "Requires the column value to exist in another table's column.",
    example: "FOREIGN KEY (user_id) REFERENCES users(id)",
    notes: "SQLite doesn't enforce FKs unless you run `PRAGMA foreign_keys = ON;`.",
  },
  {
    keyword: "REFERENCES",
    category: "constraint",
    reserved: "reserved",
    engines: ["standard", "sqlite", "postgres", "mysql", "oracle", "mssql"],
    summary: "Part of FOREIGN KEY - names the referenced table and column.",
  },
  {
    keyword: "UNIQUE",
    category: "constraint",
    reserved: "reserved",
    engines: ["standard", "sqlite", "postgres", "mysql", "oracle", "mssql"],
    summary: "No two rows can share this value (or combination of values).",
  },
  {
    keyword: "NOT NULL",
    category: "constraint",
    reserved: "reserved",
    engines: ["standard", "sqlite", "postgres", "mysql", "oracle", "mssql"],
    summary: "Column cannot be NULL.",
  },
  {
    keyword: "DEFAULT",
    category: "constraint",
    reserved: "reserved",
    engines: ["standard", "sqlite", "postgres", "mysql", "oracle", "mssql"],
    summary: "Default value if none is provided on INSERT.",
    example: "created_at TEXT DEFAULT CURRENT_TIMESTAMP",
  },
  {
    keyword: "CHECK",
    category: "constraint",
    reserved: "reserved",
    engines: ["standard", "sqlite", "postgres", "mysql", "oracle", "mssql"],
    summary: "Boolean expression that must be TRUE for every row.",
    example: "CHECK (age >= 0)",
  },
  {
    keyword: "AUTOINCREMENT",
    category: "constraint",
    reserved: "non-reserved",
    engines: ["sqlite"],
    summary: "SQLite only: forces monotonically increasing IDs (never reused).",
    notes: "Usually unnecessary - INTEGER PRIMARY KEY already auto-assigns ids.",
  },
  {
    keyword: "AUTO_INCREMENT",
    category: "constraint",
    reserved: "non-reserved",
    engines: ["mysql"],
    summary: "MySQL: columns with this produce the next integer automatically.",
  },
  {
    keyword: "IDENTITY",
    category: "constraint",
    reserved: "reserved",
    engines: ["standard", "postgres", "oracle", "mssql"],
    summary: "Modern SQL-standard form of auto-increment: `GENERATED {ALWAYS|BY DEFAULT} AS IDENTITY`.",
  },
  {
    keyword: "GENERATED",
    category: "constraint",
    reserved: "reserved",
    engines: ["standard", "sqlite", "postgres", "mysql", "oracle"],
    summary: "Declares an IDENTITY or computed column.",
    syntax: "col AS (expression) [STORED|VIRTUAL]  or  GENERATED ALWAYS AS IDENTITY",
  },
  {
    keyword: "STORED",
    category: "constraint",
    reserved: "non-reserved",
    engines: ["standard", "sqlite", "postgres", "mysql"],
    summary: "A generated column physically stored on disk.",
  },
  {
    keyword: "VIRTUAL",
    category: "constraint",
    reserved: "non-reserved",
    engines: ["sqlite", "mysql"],
    summary: "A generated column computed on read, not stored.",
  },
  {
    keyword: "COLLATE",
    category: "constraint",
    reserved: "reserved",
    engines: ["standard", "sqlite", "postgres", "mysql", "oracle", "mssql"],
    summary: "Sets the collation (sort/compare rules) for a column or expression.",
  },
  {
    keyword: "ON DELETE",
    category: "constraint",
    reserved: "non-reserved",
    engines: ["standard", "sqlite", "postgres", "mysql", "oracle", "mssql"],
    summary: "Cascade action for a foreign key when the referenced row is deleted.",
    syntax: "ON DELETE { CASCADE | SET NULL | SET DEFAULT | RESTRICT | NO ACTION }",
  },
  {
    keyword: "ON UPDATE",
    category: "constraint",
    reserved: "non-reserved",
    engines: ["standard", "sqlite", "postgres", "mysql", "oracle", "mssql"],
    summary: "Cascade action when the referenced column is updated.",
  },
  {
    keyword: "CASCADE",
    category: "constraint",
    reserved: "reserved",
    engines: ["standard", "sqlite", "postgres", "mysql", "oracle", "mssql"],
    summary: "Propagate the change (delete/update) to related rows.",
  },
  {
    keyword: "RESTRICT",
    category: "constraint",
    reserved: "reserved",
    engines: ["standard", "sqlite", "postgres", "mysql", "oracle"],
    summary: "Block the change if any related row exists.",
  },

  // -------------------------------------------------------------------------
  // Data types
  // -------------------------------------------------------------------------
  {
    keyword: "INTEGER",
    category: "datatype",
    reserved: "non-reserved",
    engines: ["standard", "sqlite", "postgres", "mysql", "oracle", "mssql"],
    summary: "Whole-number type.",
  },
  {
    keyword: "INT",
    category: "datatype",
    reserved: "non-reserved",
    engines: ["standard", "sqlite", "postgres", "mysql", "oracle", "mssql"],
    summary: "Alias for INTEGER.",
  },
  {
    keyword: "BIGINT",
    category: "datatype",
    reserved: "non-reserved",
    engines: ["standard", "postgres", "mysql", "oracle", "mssql"],
    summary: "64-bit integer.",
  },
  {
    keyword: "SMALLINT",
    category: "datatype",
    reserved: "non-reserved",
    engines: ["standard", "postgres", "mysql", "oracle", "mssql"],
    summary: "Small (usually 16-bit) integer.",
  },
  {
    keyword: "TINYINT",
    category: "datatype",
    reserved: "non-reserved",
    engines: ["mysql", "mssql"],
    summary: "8-bit integer - often used to fake booleans in MySQL.",
  },
  {
    keyword: "REAL",
    category: "datatype",
    reserved: "non-reserved",
    engines: ["standard", "sqlite", "postgres", "mssql"],
    summary: "Floating point number (8 bytes in SQLite).",
  },
  {
    keyword: "DOUBLE",
    category: "datatype",
    reserved: "non-reserved",
    engines: ["standard", "postgres", "mysql"],
    summary: "Double-precision floating point.",
  },
  {
    keyword: "FLOAT",
    category: "datatype",
    reserved: "non-reserved",
    engines: ["standard", "postgres", "mysql", "oracle", "mssql"],
    summary: "Approximate numeric type.",
  },
  {
    keyword: "NUMERIC",
    category: "datatype",
    reserved: "non-reserved",
    engines: ["standard", "sqlite", "postgres", "mysql", "oracle", "mssql"],
    summary: "Exact numeric with defined precision and scale. Use for money.",
  },
  {
    keyword: "DECIMAL",
    category: "datatype",
    reserved: "non-reserved",
    engines: ["standard", "postgres", "mysql", "oracle", "mssql"],
    summary: "Alias of NUMERIC.",
  },
  {
    keyword: "TEXT",
    category: "datatype",
    reserved: "non-reserved",
    engines: ["sqlite", "postgres", "mysql", "mssql"],
    summary: "Variable-length string.",
  },
  {
    keyword: "VARCHAR",
    category: "datatype",
    reserved: "non-reserved",
    engines: ["standard", "postgres", "mysql", "oracle", "mssql"],
    summary: "Variable-length string with a maximum length.",
  },
  {
    keyword: "CHAR",
    category: "datatype",
    reserved: "non-reserved",
    engines: ["standard", "postgres", "mysql", "oracle", "mssql"],
    summary: "Fixed-length string, padded with spaces.",
  },
  {
    keyword: "BLOB",
    category: "datatype",
    reserved: "non-reserved",
    engines: ["sqlite", "mysql", "oracle"],
    summary: "Binary large object - arbitrary bytes.",
  },
  {
    keyword: "BYTEA",
    category: "datatype",
    reserved: "non-reserved",
    engines: ["postgres"],
    summary: "Postgres binary type - equivalent to BLOB.",
  },
  {
    keyword: "BOOLEAN",
    category: "datatype",
    reserved: "non-reserved",
    engines: ["standard", "postgres", "mysql"],
    summary: "True/false type.",
    notes: "SQLite stores booleans as 0/1 INTEGERs; MySQL maps BOOLEAN to TINYINT(1).",
  },
  {
    keyword: "BOOL",
    category: "datatype",
    reserved: "non-reserved",
    engines: ["postgres", "mysql"],
    summary: "Alias of BOOLEAN.",
  },
  {
    keyword: "DATE",
    category: "datatype",
    reserved: "non-reserved",
    engines: ["standard", "postgres", "mysql", "oracle", "mssql"],
    summary: "Calendar date (year, month, day).",
  },
  {
    keyword: "TIME",
    category: "datatype",
    reserved: "non-reserved",
    engines: ["standard", "postgres", "mysql", "mssql"],
    summary: "Time of day.",
  },
  {
    keyword: "TIMESTAMP",
    category: "datatype",
    reserved: "non-reserved",
    engines: ["standard", "postgres", "mysql", "oracle"],
    summary: "Date and time.",
  },
  {
    keyword: "TIMESTAMPTZ",
    category: "datatype",
    reserved: "non-reserved",
    engines: ["postgres"],
    summary: "Timestamp with time zone (Postgres).",
  },
  {
    keyword: "DATETIME",
    category: "datatype",
    reserved: "non-reserved",
    engines: ["mysql", "mssql"],
    summary: "MySQL / MSSQL datetime type.",
  },
  {
    keyword: "INTERVAL",
    category: "datatype",
    reserved: "non-reserved",
    engines: ["standard", "postgres", "oracle"],
    summary: "Duration / time span. `INTERVAL '1 day'`.",
  },
  {
    keyword: "UUID",
    category: "datatype",
    reserved: "non-reserved",
    engines: ["postgres"],
    summary: "128-bit UUID type (Postgres).",
  },
  {
    keyword: "JSON",
    category: "datatype",
    reserved: "non-reserved",
    engines: ["postgres", "mysql"],
    summary: "Stores JSON text.",
  },
  {
    keyword: "JSONB",
    category: "datatype",
    reserved: "non-reserved",
    engines: ["postgres"],
    summary: "Binary JSON in Postgres - faster lookups, supports indexes.",
  },
  {
    keyword: "ARRAY",
    category: "datatype",
    reserved: "non-reserved",
    engines: ["postgres"],
    summary: "Postgres array type: `INTEGER[]`, `TEXT[]`, ...",
  },
  {
    keyword: "ENUM",
    category: "datatype",
    reserved: "non-reserved",
    engines: ["postgres", "mysql"],
    summary: "Fixed set of string values.",
  },

  // -------------------------------------------------------------------------
  // Functions
  // -------------------------------------------------------------------------
  {
    keyword: "COUNT",
    category: "function",
    reserved: "non-reserved",
    engines: ["standard", "sqlite", "postgres", "mysql", "oracle", "mssql"],
    summary: "Aggregate: number of rows (or non-NULL values with COUNT(col)).",
    example: "SELECT COUNT(*) FROM users;",
  },
  {
    keyword: "SUM",
    category: "function",
    reserved: "non-reserved",
    engines: ["standard", "sqlite", "postgres", "mysql", "oracle", "mssql"],
    summary: "Aggregate: total of numeric values.",
  },
  {
    keyword: "AVG",
    category: "function",
    reserved: "non-reserved",
    engines: ["standard", "sqlite", "postgres", "mysql", "oracle", "mssql"],
    summary: "Aggregate: average of numeric values (ignores NULLs).",
  },
  {
    keyword: "MIN",
    category: "function",
    reserved: "non-reserved",
    engines: ["standard", "sqlite", "postgres", "mysql", "oracle", "mssql"],
    summary: "Aggregate: smallest value.",
  },
  {
    keyword: "MAX",
    category: "function",
    reserved: "non-reserved",
    engines: ["standard", "sqlite", "postgres", "mysql", "oracle", "mssql"],
    summary: "Aggregate: largest value.",
  },
  {
    keyword: "GROUP_CONCAT",
    category: "function",
    reserved: "non-reserved",
    engines: ["sqlite", "mysql"],
    summary: "Aggregate: concatenate string values across rows.",
    example: "GROUP_CONCAT(name, ', ')",
  },
  {
    keyword: "STRING_AGG",
    category: "function",
    reserved: "non-reserved",
    engines: ["standard", "postgres", "mssql"],
    summary: "Standard alternative to GROUP_CONCAT.",
  },
  {
    keyword: "COALESCE",
    category: "function",
    reserved: "non-reserved",
    engines: ["standard", "sqlite", "postgres", "mysql", "oracle", "mssql"],
    summary: "Returns the first non-NULL argument.",
    example: "COALESCE(nickname, first_name, 'friend')",
  },
  {
    keyword: "NULLIF",
    category: "function",
    reserved: "non-reserved",
    engines: ["standard", "sqlite", "postgres", "mysql", "oracle", "mssql"],
    summary: "Returns NULL if the two arguments are equal, otherwise the first.",
    example: "NULLIF(divisor, 0)",
  },
  {
    keyword: "IFNULL",
    category: "function",
    reserved: "non-reserved",
    engines: ["sqlite", "mysql"],
    summary: "Returns the second value if the first is NULL (two-arg COALESCE).",
  },
  {
    keyword: "ISNULL",
    category: "function",
    reserved: "non-reserved",
    engines: ["mysql", "mssql"],
    summary: "MySQL: test for NULL. MSSQL: COALESCE-style replacement.",
  },
  {
    keyword: "CAST",
    category: "function",
    reserved: "reserved",
    engines: ["standard", "sqlite", "postgres", "mysql", "oracle", "mssql"],
    summary: "Convert a value to a different type.",
    example: "CAST(score AS INTEGER)",
  },
  {
    keyword: "CONVERT",
    category: "function",
    reserved: "reserved",
    engines: ["mysql", "mssql"],
    summary: "MSSQL/MySQL type-conversion function.",
  },
  {
    keyword: "CASE",
    category: "function",
    reserved: "reserved",
    engines: ["standard", "sqlite", "postgres", "mysql", "oracle", "mssql"],
    summary: "Conditional expression - SQL's if/else.",
    syntax: "CASE WHEN cond THEN v [WHEN ...] [ELSE default] END",
  },
  {
    keyword: "WHEN",
    category: "function",
    reserved: "reserved",
    engines: ["standard", "sqlite", "postgres", "mysql", "oracle", "mssql"],
    summary: "Part of CASE - a condition branch.",
  },
  {
    keyword: "THEN",
    category: "function",
    reserved: "reserved",
    engines: ["standard", "sqlite", "postgres", "mysql", "oracle", "mssql"],
    summary: "Part of CASE - the branch's result.",
  },
  {
    keyword: "ELSE",
    category: "function",
    reserved: "reserved",
    engines: ["standard", "sqlite", "postgres", "mysql", "oracle", "mssql"],
    summary: "Default branch of CASE.",
  },
  {
    keyword: "END",
    category: "function",
    reserved: "reserved",
    engines: ["standard", "sqlite", "postgres", "mysql", "oracle", "mssql"],
    summary: "Closes a CASE expression or BEGIN block.",
  },
  {
    keyword: "SUBSTR",
    category: "function",
    reserved: "non-reserved",
    engines: ["sqlite", "postgres", "mysql", "oracle"],
    summary: "Substring extraction. `SUBSTR(str, start, length)`.",
  },
  {
    keyword: "SUBSTRING",
    category: "function",
    reserved: "reserved",
    engines: ["standard", "postgres", "mysql", "mssql"],
    summary: "Standard spelling of SUBSTR.",
  },
  {
    keyword: "LENGTH",
    category: "function",
    reserved: "non-reserved",
    engines: ["standard", "sqlite", "postgres", "mysql"],
    summary: "Length of a string.",
  },
  {
    keyword: "LEN",
    category: "function",
    reserved: "non-reserved",
    engines: ["mssql"],
    summary: "MSSQL: length of a string.",
  },
  {
    keyword: "UPPER",
    category: "function",
    reserved: "non-reserved",
    engines: ["standard", "sqlite", "postgres", "mysql", "oracle", "mssql"],
    summary: "Uppercase a string.",
  },
  {
    keyword: "LOWER",
    category: "function",
    reserved: "non-reserved",
    engines: ["standard", "sqlite", "postgres", "mysql", "oracle", "mssql"],
    summary: "Lowercase a string.",
  },
  {
    keyword: "TRIM",
    category: "function",
    reserved: "reserved",
    engines: ["standard", "sqlite", "postgres", "mysql", "oracle", "mssql"],
    summary: "Strip characters from the start/end of a string.",
  },
  {
    keyword: "REPLACE",
    category: "function",
    reserved: "non-reserved",
    engines: ["standard", "sqlite", "postgres", "mysql", "oracle", "mssql"],
    summary: "Replace occurrences of one substring with another.",
  },
  {
    keyword: "CONCAT",
    category: "function",
    reserved: "non-reserved",
    engines: ["standard", "postgres", "mysql", "oracle", "mssql"],
    summary: "Concatenate strings. SQLite uses the `||` operator instead.",
  },
  {
    keyword: "ROUND",
    category: "function",
    reserved: "non-reserved",
    engines: ["standard", "sqlite", "postgres", "mysql", "oracle", "mssql"],
    summary: "Round a number to N decimal places.",
  },
  {
    keyword: "ABS",
    category: "function",
    reserved: "non-reserved",
    engines: ["standard", "sqlite", "postgres", "mysql", "oracle", "mssql"],
    summary: "Absolute value.",
  },
  {
    keyword: "CURRENT_TIMESTAMP",
    category: "function",
    reserved: "reserved",
    engines: ["standard", "sqlite", "postgres", "mysql", "oracle", "mssql"],
    summary: "Current date-time in the server's timezone. No parentheses.",
  },
  {
    keyword: "CURRENT_DATE",
    category: "function",
    reserved: "reserved",
    engines: ["standard", "sqlite", "postgres", "mysql", "oracle", "mssql"],
    summary: "Current date.",
  },
  {
    keyword: "CURRENT_TIME",
    category: "function",
    reserved: "reserved",
    engines: ["standard", "sqlite", "postgres", "mysql", "oracle"],
    summary: "Current time of day.",
  },
  {
    keyword: "NOW",
    category: "function",
    reserved: "non-reserved",
    engines: ["postgres", "mysql"],
    summary: "Function form of CURRENT_TIMESTAMP: `NOW()`.",
  },
  {
    keyword: "DATE",
    category: "function",
    reserved: "reserved",
    engines: ["sqlite", "mysql"],
    summary: "Also a function: strip the time component. `DATE('2024-01-02 10:30')`.",
  },
  {
    keyword: "STRFTIME",
    category: "function",
    reserved: "non-reserved",
    engines: ["sqlite"],
    summary: "Format a date in SQLite: `strftime('%Y-%m', col)`.",
  },
  {
    keyword: "DATE_TRUNC",
    category: "function",
    reserved: "non-reserved",
    engines: ["postgres"],
    summary: "Truncate a timestamp to a precision (day, month, year, ...).",
  },
  {
    keyword: "EXTRACT",
    category: "function",
    reserved: "reserved",
    engines: ["standard", "postgres", "mysql", "oracle"],
    summary: "Pull a field (year, month, day, ...) out of a date/timestamp.",
  },
  {
    keyword: "ROW_NUMBER",
    category: "function",
    reserved: "reserved",
    engines: ["standard", "sqlite", "postgres", "mysql", "oracle", "mssql"],
    summary: "Window function: 1, 2, 3, ... within each partition.",
  },
  {
    keyword: "RANK",
    category: "function",
    reserved: "reserved",
    engines: ["standard", "sqlite", "postgres", "mysql", "oracle", "mssql"],
    summary: "Window function: ranking with gaps after ties.",
  },
  {
    keyword: "DENSE_RANK",
    category: "function",
    reserved: "reserved",
    engines: ["standard", "sqlite", "postgres", "mysql", "oracle", "mssql"],
    summary: "Window function: ranking with no gaps after ties.",
  },
  {
    keyword: "NTILE",
    category: "function",
    reserved: "reserved",
    engines: ["standard", "sqlite", "postgres", "mysql", "oracle", "mssql"],
    summary: "Window function: bucket rows into N roughly-equal groups.",
  },
  {
    keyword: "LAG",
    category: "function",
    reserved: "reserved",
    engines: ["standard", "sqlite", "postgres", "mysql", "oracle", "mssql"],
    summary: "Window function: value from a previous row.",
  },
  {
    keyword: "LEAD",
    category: "function",
    reserved: "reserved",
    engines: ["standard", "sqlite", "postgres", "mysql", "oracle", "mssql"],
    summary: "Window function: value from a following row.",
  },
  {
    keyword: "FIRST_VALUE",
    category: "function",
    reserved: "reserved",
    engines: ["standard", "sqlite", "postgres", "mysql", "oracle", "mssql"],
    summary: "Window function: first value in the window frame.",
  },
  {
    keyword: "LAST_VALUE",
    category: "function",
    reserved: "reserved",
    engines: ["standard", "sqlite", "postgres", "mysql", "oracle", "mssql"],
    summary: "Window function: last value in the window frame.",
  },
  {
    keyword: "PERCENT_RANK",
    category: "function",
    reserved: "reserved",
    engines: ["standard", "sqlite", "postgres", "mysql", "oracle"],
    summary: "Window function: relative rank in [0, 1].",
  },

  // -------------------------------------------------------------------------
  // TCL
  // -------------------------------------------------------------------------
  {
    keyword: "BEGIN",
    category: "tcl",
    reserved: "reserved",
    engines: ["standard", "sqlite", "postgres", "mysql", "oracle", "mssql"],
    summary: "Start a transaction.",
  },
  {
    keyword: "START TRANSACTION",
    category: "tcl",
    reserved: "non-reserved",
    engines: ["standard", "postgres", "mysql"],
    summary: "SQL-standard way to start a transaction.",
  },
  {
    keyword: "COMMIT",
    category: "tcl",
    reserved: "reserved",
    engines: ["standard", "sqlite", "postgres", "mysql", "oracle", "mssql"],
    summary: "Make pending changes permanent.",
  },
  {
    keyword: "ROLLBACK",
    category: "tcl",
    reserved: "reserved",
    engines: ["standard", "sqlite", "postgres", "mysql", "oracle", "mssql"],
    summary: "Undo pending changes.",
  },
  {
    keyword: "SAVEPOINT",
    category: "tcl",
    reserved: "reserved",
    engines: ["standard", "sqlite", "postgres", "mysql", "oracle"],
    summary: "Named marker inside a transaction; ROLLBACK TO SAVEPOINT rewinds to it.",
  },
  {
    keyword: "RELEASE SAVEPOINT",
    category: "tcl",
    reserved: "non-reserved",
    engines: ["standard", "sqlite", "postgres", "mysql", "oracle"],
    summary: "Discard a savepoint.",
  },

  // -------------------------------------------------------------------------
  // DCL
  // -------------------------------------------------------------------------
  {
    keyword: "GRANT",
    category: "dcl",
    reserved: "reserved",
    engines: ["standard", "postgres", "mysql", "oracle", "mssql"],
    summary: "Give a user/role permissions on a database object.",
  },
  {
    keyword: "REVOKE",
    category: "dcl",
    reserved: "reserved",
    engines: ["standard", "postgres", "mysql", "oracle", "mssql"],
    summary: "Take back permissions granted earlier.",
  },
  {
    keyword: "ROLE",
    category: "dcl",
    reserved: "reserved",
    engines: ["standard", "postgres", "mysql", "oracle", "mssql"],
    summary: "A named group of privileges, assignable to users.",
  },

  // -------------------------------------------------------------------------
  // Literals
  // -------------------------------------------------------------------------
  {
    keyword: "NULL",
    category: "literal",
    reserved: "reserved",
    engines: ["standard", "sqlite", "postgres", "mysql", "oracle", "mssql"],
    summary: "Unknown / missing value. Compare with IS NULL, not `=`.",
  },
  {
    keyword: "TRUE",
    category: "literal",
    reserved: "reserved",
    engines: ["standard", "sqlite", "postgres", "mysql"],
    summary: "Boolean true literal.",
  },
  {
    keyword: "FALSE",
    category: "literal",
    reserved: "reserved",
    engines: ["standard", "sqlite", "postgres", "mysql"],
    summary: "Boolean false literal.",
  },
  {
    keyword: "UNKNOWN",
    category: "literal",
    reserved: "reserved",
    engines: ["standard", "postgres"],
    summary: "Three-valued-logic literal - the result of boolean ops involving NULL.",
  },

  // -------------------------------------------------------------------------
  // Meta / tooling
  // -------------------------------------------------------------------------
  {
    keyword: "EXPLAIN",
    category: "meta",
    reserved: "non-reserved",
    engines: ["sqlite", "postgres", "mysql"],
    summary: "Show the query plan the engine would use.",
  },
  {
    keyword: "EXPLAIN QUERY PLAN",
    category: "meta",
    reserved: "non-reserved",
    engines: ["sqlite"],
    summary: "SQLite-specific: human-readable query plan.",
  },
  {
    keyword: "ANALYZE",
    category: "meta",
    reserved: "reserved",
    engines: ["sqlite", "postgres", "mysql"],
    summary: "Collect statistics the query planner uses.",
  },
  {
    keyword: "VACUUM",
    category: "meta",
    reserved: "reserved",
    engines: ["sqlite", "postgres"],
    summary: "Reclaim storage and defragment the database file.",
  },
  {
    keyword: "PRAGMA",
    category: "meta",
    reserved: "reserved",
    engines: ["sqlite"],
    summary: "SQLite configuration / introspection statement.",
    example: "PRAGMA foreign_keys = ON;",
  },
  {
    keyword: "SHOW",
    category: "meta",
    reserved: "reserved",
    engines: ["postgres", "mysql"],
    summary: "Display server settings or metadata (e.g. `SHOW TABLES`, `SHOW search_path`).",
  },
  {
    keyword: "DESCRIBE",
    category: "meta",
    reserved: "reserved",
    engines: ["mysql", "oracle"],
    summary: "Show a table's columns. SQLite uses `PRAGMA table_info(name)`.",
  },

  // -------------------------------------------------------------------------
  // Misc / flow control keywords commonly seen
  // -------------------------------------------------------------------------
  {
    keyword: "ASC",
    category: "clause",
    reserved: "reserved",
    engines: ["standard", "sqlite", "postgres", "mysql", "oracle", "mssql"],
    summary: "Ascending sort (default).",
  },
  {
    keyword: "DESC",
    category: "clause",
    reserved: "reserved",
    engines: ["standard", "sqlite", "postgres", "mysql", "oracle", "mssql"],
    summary: "Descending sort.",
  },
  {
    keyword: "NULLS FIRST",
    category: "clause",
    reserved: "non-reserved",
    engines: ["standard", "sqlite", "postgres", "oracle"],
    summary: "Place NULL values at the start of an ORDER BY result.",
  },
  {
    keyword: "NULLS LAST",
    category: "clause",
    reserved: "non-reserved",
    engines: ["standard", "sqlite", "postgres", "oracle"],
    summary: "Place NULL values at the end of an ORDER BY result.",
  },
  {
    keyword: "FILTER",
    category: "clause",
    reserved: "reserved",
    engines: ["standard", "sqlite", "postgres"],
    summary: "Per-aggregate filter: `SUM(x) FILTER (WHERE status = 'paid')`.",
  },
  {
    keyword: "ROWS",
    category: "clause",
    reserved: "reserved",
    engines: ["standard", "sqlite", "postgres", "mysql", "oracle", "mssql"],
    summary: "Window frame unit (row-based).",
  },
  {
    keyword: "RANGE",
    category: "clause",
    reserved: "reserved",
    engines: ["standard", "sqlite", "postgres", "mysql", "oracle", "mssql"],
    summary: "Window frame unit (value-based).",
  },
  {
    keyword: "GROUPS",
    category: "clause",
    reserved: "reserved",
    engines: ["standard", "postgres", "oracle"],
    summary: "Window frame unit (peer-group-based).",
  },
  {
    keyword: "PRECEDING",
    category: "clause",
    reserved: "reserved",
    engines: ["standard", "sqlite", "postgres", "mysql", "oracle", "mssql"],
    summary: "Window frame boundary: rows before the current row.",
  },
  {
    keyword: "FOLLOWING",
    category: "clause",
    reserved: "reserved",
    engines: ["standard", "sqlite", "postgres", "mysql", "oracle", "mssql"],
    summary: "Window frame boundary: rows after the current row.",
  },
  {
    keyword: "UNBOUNDED",
    category: "clause",
    reserved: "reserved",
    engines: ["standard", "sqlite", "postgres", "mysql", "oracle", "mssql"],
    summary: "Window frame: from the start / to the end of the partition.",
  },
  {
    keyword: "CURRENT ROW",
    category: "clause",
    reserved: "reserved",
    engines: ["standard", "sqlite", "postgres", "mysql", "oracle", "mssql"],
    summary: "Window frame boundary: the current row.",
  },
  {
    keyword: "LOCK",
    category: "tcl",
    reserved: "reserved",
    engines: ["postgres", "mysql", "oracle"],
    summary: "Acquire a table/row lock.",
  },
  {
    keyword: "FOR UPDATE",
    category: "clause",
    reserved: "non-reserved",
    engines: ["standard", "postgres", "mysql", "oracle"],
    summary: "Row-level lock for subsequent UPDATE in the same transaction.",
  },
  {
    keyword: "FOR SHARE",
    category: "clause",
    reserved: "non-reserved",
    engines: ["standard", "postgres", "mysql"],
    summary: "Shared row lock (other readers OK, writers blocked).",
  },
  {
    keyword: "SKIP LOCKED",
    category: "clause",
    reserved: "non-reserved",
    engines: ["standard", "postgres", "mysql", "oracle"],
    summary: "Skip rows another transaction has locked.",
  },
  {
    keyword: "NOWAIT",
    category: "clause",
    reserved: "non-reserved",
    engines: ["standard", "postgres", "mysql", "oracle"],
    summary: "Error immediately if a required lock can't be acquired.",
  },
];
