import { Challenge } from "@/types/challenge";
import { ECOMMERCE_SEED, EMPLOYEES_SEED } from "../seed-data";

export const complexChallenges: Challenge[] = [
  {
    id: "cx-01",
    title: "Top 3 Highest-Paid per Department",
    description: "For each department, return the **3 highest-paid employees**. Return department_id, first_name, salary ordered by department_id asc, salary desc.",
    category: "complex-queries",
    difficulty: "advanced",
    seedSQL: EMPLOYEES_SEED,
    expectedColumns: ["department_id", "first_name", "salary"],
    expectedOutput: [
      [1, "Eva", 105000.0],
      [1, "Alice", 95000.0],
      [1, "Jack", 92000.0],
      [2, "Carol", 72000.0],
      [2, "Leo", 69000.0],
      [2, "Frank", 65000.0],
      [3, "Grace", 78000.0],
      [3, "Karen", 71000.0],
      [3, "David", 68000.0],
      [4, "Henry", 62000.0],
      [4, "Noah", 58000.0],
      [5, "Mia", 91000.0],
      [5, "Iris", 85000.0],
    ],
    hints: [
      "Use ROW_NUMBER() OVER (PARTITION BY department_id ORDER BY salary DESC).",
      "Wrap it in a subquery and filter WHERE rk <= 3.",
      "SELECT * FROM (SELECT ..., ROW_NUMBER() OVER (PARTITION BY department_id ORDER BY salary DESC) AS rk FROM employees) WHERE rk <= 3",
    ],
    orderMatters: true,
    expectedQuery: "SELECT department_id, first_name, salary FROM (  SELECT department_id, first_name, salary,          ROW_NUMBER() OVER (PARTITION BY department_id ORDER BY salary DESC) AS rk   FROM employees) t WHERE rk <= 3 ORDER BY department_id, salary DESC",
  },
  {
    id: "cx-02",
    title: "Customer Lifetime Value",
    description: "For each customer, compute order_count, total_spent (rounded 2), and avg_order_value (rounded 2). Include customers with ZERO orders (they should show 0/0.0). Return customer_id, order_count, total_spent, avg_order_value ordered by total_spent desc, customer_id asc.",
    category: "complex-queries",
    difficulty: "advanced",
    seedSQL: ECOMMERCE_SEED,
    expectedColumns: ["customer_id", "order_count", "total_spent", "avg_order_value"],
    expectedOutput: [
      [8, 1, 1749.98, 1749.98],
      [1, 2, 1519.95, 759.98],
      [4, 1, 1299.99, 1299.99],
      [2, 2, 939.97, 469.99],
      [5, 1, 699.98, 699.98],
      [6, 1, 89.99, 89.99],
      [7, 1, 47.98, 47.98],
      [3, 1, 29.99, 29.99],
    ],
    hints: [
      "LEFT JOIN ensures customers with no orders still appear.",
      "Use COALESCE(SUM(...), 0) so NULLs become 0.",
      "GROUP BY c.id, then aggregate.",
    ],
    orderMatters: true,
    expectedQuery: "SELECT c.id AS customer_id,        COUNT(o.id) AS order_count,        ROUND(COALESCE(SUM(o.total), 0), 2) AS total_spent,        ROUND(COALESCE(AVG(o.total), 0), 2) AS avg_order_value FROM customers c LEFT JOIN orders o ON o.customer_id = c.id GROUP BY c.id ORDER BY total_spent DESC, customer_id",
  },
  {
    id: "cx-03",
    title: "Month-over-Month Revenue",
    description: "Compute monthly revenue and the change versus the previous month. Return month (YYYY-MM), revenue (rounded 2), and change (revenue - previous month, rounded 2; NULL for the first month). Order by month ascending.",
    category: "complex-queries",
    difficulty: "expert",
    seedSQL: ECOMMERCE_SEED,
    expectedColumns: ["month", "revenue", "change"],
    expectedOutput: [
      ["2024-01", 1899.94, null],
      ["2024-02", 2139.95, 240.01],
      ["2024-03", 2337.94, 197.99],
    ],
    hints: [
      "Extract month with SUBSTR(order_date, 1, 7).",
      "Use LAG(revenue) OVER (ORDER BY month) for previous month.",
      "ROUND the difference to 2 decimals.",
    ],
    orderMatters: true,
    expectedQuery: "WITH m AS (SELECT SUBSTR(order_date, 1, 7) AS month, ROUND(SUM(total), 2) AS revenue            FROM orders GROUP BY month) SELECT month, revenue, ROUND(revenue - LAG(revenue) OVER (ORDER BY month), 2) AS change FROM m ORDER BY month",
  },
  {
    id: "cx-04",
    title: "Recursive Org Chart Depth",
    description: "Using a **recursive CTE**, compute each employee's depth in the management hierarchy (top-level managers with manager_id IS NULL are depth 0). Return id, first_name, depth ordered by depth asc, id asc.",
    category: "complex-queries",
    difficulty: "expert",
    seedSQL: EMPLOYEES_SEED,
    expectedColumns: ["id", "first_name", "depth"],
    expectedOutput: [
      [1, "Alice", 0],
      [3, "Carol", 0],
      [4, "David", 0],
      [5, "Eva", 0],
      [8, "Henry", 0],
      [9, "Iris", 0],
      [2, "Bob", 1],
      [6, "Frank", 1],
      [7, "Grace", 1],
      [10, "Jack", 1],
      [11, "Karen", 1],
      [12, "Leo", 1],
      [13, "Mia", 1],
      [14, "Noah", 1],
      [15, "Olivia", 1],
    ],
    hints: [
      "Recursive CTE: base case (top-level managers) UNION ALL recursive step.",
      "Each recursive step joins employees to the CTE on manager_id = parent id.",
      "WITH RECURSIVE chart AS (... UNION ALL ...) SELECT * FROM chart;",
    ],
    orderMatters: true,
    expectedQuery: "WITH RECURSIVE chart AS (  SELECT id, first_name, 0 AS depth FROM employees WHERE manager_id IS NULL   UNION ALL   SELECT e.id, e.first_name, c.depth + 1 FROM employees e   JOIN chart c ON e.manager_id = c.id) SELECT id, first_name, depth FROM chart ORDER BY depth, id",
  },
  {
    id: "cx-05",
    title: "Category Share of Total Revenue",
    description: "For each product category, compute total revenue (from order_items: quantity * unit_price), its share of overall revenue (percentage, rounded 2), ordered by revenue desc. Return category, revenue, share_pct.",
    category: "complex-queries",
    difficulty: "advanced",
    seedSQL: ECOMMERCE_SEED,
    expectedColumns: ["category", "revenue", "share_pct"],
    expectedOutput: [
      ["Electronics", 4809.88, 75.5],
      ["Office", 1560.94, 24.5],
    ],
    hints: [
      "Aggregate per category first (CTE).",
      "Divide each category's revenue by (SELECT SUM(revenue) FROM cat).",
      "Multiply by 100.0 to get a percentage.",
    ],
    orderMatters: true,
    expectedQuery: "WITH cat AS (  SELECT p.category, SUM(oi.quantity * oi.unit_price) AS revenue   FROM order_items oi JOIN products p ON p.id = oi.product_id   GROUP BY p.category) SELECT category, ROUND(revenue, 2) AS revenue,   ROUND(revenue * 100.0 / (SELECT SUM(revenue) FROM cat), 2) AS share_pct FROM cat ORDER BY revenue DESC",
  },
  {
    id: "cx-06",
    title: "Customers Who Shopped Multiple Categories",
    description: "Find customers who have purchased products from **more than one category**. Return customer_id and distinct_categories ordered by distinct_categories desc, customer_id asc.",
    category: "complex-queries",
    difficulty: "advanced",
    seedSQL: ECOMMERCE_SEED,
    expectedColumns: ["customer_id", "distinct_categories"],
    expectedOutput: [
      [2, 2],
      [5, 2],
      [8, 2],
    ],
    hints: [
      "Join orders -> order_items -> products so each purchase has a category.",
      "Group by customer_id and COUNT(DISTINCT p.category).",
      "HAVING COUNT(DISTINCT p.category) > 1 keeps only multi-category shoppers.",
    ],
    orderMatters: true,
    expectedQuery: "SELECT o.customer_id, COUNT(DISTINCT p.category) AS distinct_categories FROM orders o JOIN order_items oi ON oi.order_id = o.id JOIN products p ON p.id = oi.product_id GROUP BY o.customer_id HAVING COUNT(DISTINCT p.category) > 1 ORDER BY distinct_categories DESC, o.customer_id",
  },
  {
    id: "cx-07",
    title: "Self-Join: Salary Gap to Manager",
    description: "For each employee who has a manager, return first_name, manager_name, and the salary gap (manager's salary - employee's salary). Positive means the manager earns more. Order by gap desc, first_name asc.",
    category: "complex-queries",
    difficulty: "intermediate",
    seedSQL: EMPLOYEES_SEED,
    expectedColumns: ["first_name", "manager_name", "gap"],
    expectedOutput: [
      ["Olivia", "Alice", 17000.0],
      ["Jack", "Eva", 13000.0],
      ["Bob", "Alice", 7000.0],
      ["Frank", "Carol", 7000.0],
      ["Noah", "Henry", 4000.0],
      ["Leo", "Carol", 3000.0],
      ["Karen", "David", -3000.0],
      ["Mia", "Iris", -6000.0],
      ["Grace", "David", -10000.0],
    ],
    hints: [
      "Join employees to itself on e.manager_id = m.id.",
      "Use aliases like e (employee) and m (manager) to disambiguate.",
      "SELECT e.first_name, m.first_name AS manager_name, (m.salary - e.salary) AS gap FROM employees e JOIN employees m ON m.id = e.manager_id",
    ],
    orderMatters: true,
    expectedQuery: "SELECT e.first_name, m.first_name AS manager_name,        (m.salary - e.salary) AS gap FROM employees e JOIN employees m ON m.id = e.manager_id ORDER BY gap DESC, e.first_name",
  },
  {
    id: "cx-08",
    title: "Pivot: Orders by Status per Month",
    description: "Pivot orders: for each month return counts per status. Return month, completed, shipped, pending (0 when no orders of that status). Order by month asc.",
    category: "complex-queries",
    difficulty: "advanced",
    seedSQL: ECOMMERCE_SEED,
    expectedColumns: ["month", "completed", "shipped", "pending"],
    expectedOutput: [
      ["2024-01", 3, 0, 0],
      ["2024-02", 2, 1, 0],
      ["2024-03", 2, 1, 1],
    ],
    hints: [
      "Use SUM(CASE WHEN ... THEN 1 ELSE 0 END) to count matching rows per group.",
      "Group by the month derived from SUBSTR(order_date, 1, 7).",
      "SELECT SUBSTR(order_date, 1, 7) AS month, SUM(CASE WHEN status = 'completed' THEN 1 ELSE 0 END) AS completed, ...",
    ],
    orderMatters: true,
    expectedQuery: "SELECT SUBSTR(order_date, 1, 7) AS month,        SUM(CASE WHEN status = 'completed' THEN 1 ELSE 0 END) AS completed,        SUM(CASE WHEN status = 'shipped' THEN 1 ELSE 0 END) AS shipped,        SUM(CASE WHEN status = 'pending' THEN 1 ELSE 0 END) AS pending FROM orders GROUP BY month ORDER BY month",
  },
];
