import { Challenge } from "@/types/challenge";
import { ECOMMERCE_SEED, EMPLOYEES_SEED } from "../seed-data";

export const havingChallenges: Challenge[] = [
  {
    id: "hav-01",
    title: "Busy Departments",
    description: "List departments with **3 or more employees**. Return department_id and employee_count, ordered by employee_count descending.",
    category: "having",
    difficulty: "intermediate",
    seedSQL: EMPLOYEES_SEED,
    expectedColumns: ["department_id", "employee_count"],
    expectedOutput: [
      [1, 5],
      [2, 3],
      [3, 3],
    ],
    hints: [
      "GROUP BY first, then filter groups with HAVING.",
      "HAVING works on aggregate results, WHERE works on raw rows.",
      "SELECT department_id, COUNT(*) AS employee_count FROM employees GROUP BY department_id HAVING COUNT(*) >= 3 ORDER BY employee_count DESC, department_id",
    ],
    orderMatters: true,
    expectedQuery: "SELECT department_id, COUNT(*) AS employee_count FROM employees GROUP BY department_id HAVING COUNT(*) >= 3 ORDER BY employee_count DESC, department_id",
  },
  {
    id: "hav-02",
    title: "Repeat Customers",
    description: "Find customers who have placed **more than one order**. Return customer_id and order_count ordered by order_count descending.",
    category: "having",
    difficulty: "intermediate",
    seedSQL: ECOMMERCE_SEED,
    expectedColumns: ["customer_id", "order_count"],
    expectedOutput: [
      [1, 2],
      [2, 2],
    ],
    hints: [
      "Group by customer_id.",
      "HAVING COUNT(*) > 1 keeps only repeat buyers.",
      "SELECT customer_id, COUNT(*) AS order_count FROM orders GROUP BY customer_id HAVING COUNT(*) > 1 ORDER BY order_count DESC, customer_id",
    ],
    orderMatters: true,
    expectedQuery: "SELECT customer_id, COUNT(*) AS order_count FROM orders GROUP BY customer_id HAVING COUNT(*) > 1 ORDER BY order_count DESC, customer_id",
  },
  {
    id: "hav-03",
    title: "Highly Rated Products",
    description: "Find products with an **average review rating of 4.5 or higher** AND at least 2 reviews. Return product_id, avg_rating (rounded to 2 decimals), and review_count, ordered by avg_rating desc.",
    category: "having",
    difficulty: "intermediate",
    seedSQL: ECOMMERCE_SEED,
    expectedColumns: ["product_id", "avg_rating", "review_count"],
    expectedOutput: [
      [1, 4.67, 3],
    ],
    hints: [
      "HAVING can combine multiple conditions with AND.",
      "Use ROUND(AVG(rating), 2) for the average.",
      "SELECT product_id, ROUND(AVG(rating), 2) AS avg_rating, COUNT(*) AS review_count FROM reviews GROUP BY product_id HAVING AVG(rating) >= 4.5 AND COUNT(*) >= 2 ORDER BY avg_rating DESC, product_id",
    ],
    orderMatters: true,
    expectedQuery: "SELECT product_id, ROUND(AVG(rating), 2) AS avg_rating, COUNT(*) AS review_count FROM reviews GROUP BY product_id HAVING AVG(rating) >= 4.5 AND COUNT(*) >= 2 ORDER BY avg_rating DESC, product_id",
  },
  {
    id: "hav-04",
    title: "Categories With Deep Inventory",
    description: "Show product categories whose **total stock exceeds 400 units**. Return category and total_stock, ordered by total_stock desc.",
    category: "having",
    difficulty: "beginner",
    seedSQL: ECOMMERCE_SEED,
    expectedColumns: ["category", "total_stock"],
    expectedOutput: [
      ["Office", 645],
      ["Electronics", 590],
    ],
    hints: [
      "Aggregate SUM(stock) per category.",
      "Use HAVING to filter aggregated totals (not WHERE).",
      "SELECT category, SUM(stock) AS total_stock FROM products GROUP BY category HAVING SUM(stock) > 400 ORDER BY total_stock DESC",
    ],
    orderMatters: true,
    expectedQuery: "SELECT category, SUM(stock) AS total_stock FROM products GROUP BY category HAVING SUM(stock) > 400 ORDER BY total_stock DESC",
  },
  {
    id: "hav-05",
    title: "Managers With a Team",
    description: "Find managers who have **2 or more direct reports**. Return manager_id and report_count ordered by report_count desc.",
    category: "having",
    difficulty: "intermediate",
    seedSQL: EMPLOYEES_SEED,
    expectedColumns: ["manager_id", "report_count"],
    expectedOutput: [
      [1, 2],
      [3, 2],
      [4, 2],
    ],
    hints: [
      "Filter NULL manager_ids first with WHERE.",
      "Then GROUP BY manager_id and HAVING COUNT(*) >= 2.",
      "SELECT manager_id, COUNT(*) AS report_count FROM employees WHERE manager_id IS NOT NULL GROUP BY manager_id HAVING COUNT(*) >= 2 ORDER BY report_count DESC, manager_id",
    ],
    orderMatters: true,
    expectedQuery: "SELECT manager_id, COUNT(*) AS report_count FROM employees WHERE manager_id IS NOT NULL GROUP BY manager_id HAVING COUNT(*) >= 2 ORDER BY report_count DESC, manager_id",
  },
  {
    id: "hav-06",
    title: "Hiring Years With Multiple Hires",
    description: "List years in which **2 or more employees were hired**. Return hire_year and hires, ordered by hire_year ascending.",
    category: "having",
    difficulty: "intermediate",
    seedSQL: EMPLOYEES_SEED,
    expectedColumns: ["hire_year", "hires"],
    expectedOutput: [
      ["2019", 2],
      ["2020", 4],
      ["2021", 2],
      ["2022", 3],
      ["2023", 3],
    ],
    hints: [
      "Extract the year using SUBSTR(hire_date, 1, 4) or strftime('%Y', hire_date).",
      "Group by the year, then HAVING COUNT(*) >= 2.",
      "SELECT SUBSTR(hire_date, 1, 4) AS hire_year, COUNT(*) AS hires FROM employees GROUP BY hire_year HAVING COUNT(*) >= 2 ORDER BY hire_year",
    ],
    orderMatters: true,
    expectedQuery: "SELECT SUBSTR(hire_date, 1, 4) AS hire_year, COUNT(*) AS hires FROM employees GROUP BY hire_year HAVING COUNT(*) >= 2 ORDER BY hire_year",
  },
  {
    id: "hav-07",
    title: "Big Spenders",
    description: "List customers who have spent **more than 1000 total** across all their orders. Return customer_id and total_spent (rounded to 2 decimals), ordered by total_spent desc.",
    category: "having",
    difficulty: "intermediate",
    seedSQL: ECOMMERCE_SEED,
    expectedColumns: ["customer_id", "total_spent"],
    expectedOutput: [
      [8, 1749.98],
      [1, 1519.95],
      [4, 1299.99],
    ],
    hints: [
      "Aggregate SUM(total) per customer_id.",
      "HAVING SUM(total) > 1000 filters big spenders.",
      "SELECT customer_id, ROUND(SUM(total), 2) AS total_spent FROM orders GROUP BY customer_id HAVING SUM(total) > 1000 ORDER BY total_spent DESC, customer_id",
    ],
    orderMatters: true,
    expectedQuery: "SELECT customer_id, ROUND(SUM(total), 2) AS total_spent FROM orders GROUP BY customer_id HAVING SUM(total) > 1000 ORDER BY total_spent DESC, customer_id",
  },
];
