import { Challenge } from "@/types/challenge";

export const constraintsChallenges: Challenge[] = [
  {
    id: "con-01",
    title: "NOT NULL Enforcement",
    description: "Create a table `users(id INTEGER PRIMARY KEY, email TEXT NOT NULL)`, insert two valid rows and one invalid row (NULL email) using `INSERT OR IGNORE`. Finally `SELECT id, email FROM users ORDER BY id`.",
    category: "constraints",
    difficulty: "beginner",
    seedSQL: "",
    expectedColumns: ["id", "email"],
    expectedOutput: [
      [1, "a@x.com"],
      [2, "b@x.com"],
    ],
    hints: [
      "NOT NULL rejects NULL values on insert.",
      "INSERT OR IGNORE swallows constraint violations silently.",
      "CREATE TABLE users (... email TEXT NOT NULL);",
    ],
    orderMatters: true,
    expectedQuery: "CREATE TABLE users (id INTEGER PRIMARY KEY, email TEXT NOT NULL);\nINSERT INTO users VALUES (1, 'a@x.com');\nINSERT INTO users VALUES (2, 'b@x.com');\nINSERT OR IGNORE INTO users VALUES (3, NULL);\nSELECT id, email FROM users ORDER BY id;",
  },
  {
    id: "con-02",
    title: "UNIQUE Constraint",
    description: "Create `emails(id INTEGER PRIMARY KEY, address TEXT UNIQUE)`, insert three rows where the third tries to duplicate the first (use `INSERT OR IGNORE`). Then `SELECT id, address FROM emails ORDER BY id`.",
    category: "constraints",
    difficulty: "beginner",
    seedSQL: "",
    expectedColumns: ["id", "address"],
    expectedOutput: [
      [1, "a@x.com"],
      [2, "b@x.com"],
    ],
    hints: [
      "UNIQUE rejects duplicate values.",
      "INSERT OR IGNORE lets the batch continue past the violation.",
      "CREATE TABLE emails (... address TEXT UNIQUE);",
    ],
    orderMatters: true,
    expectedQuery: "CREATE TABLE emails (id INTEGER PRIMARY KEY, address TEXT UNIQUE);\nINSERT INTO emails VALUES (1, 'a@x.com');\nINSERT INTO emails VALUES (2, 'b@x.com');\nINSERT OR IGNORE INTO emails VALUES (3, 'a@x.com');\nSELECT id, address FROM emails ORDER BY id;",
  },
  {
    id: "con-03",
    title: "CHECK Constraint",
    description: "Create `products(id INTEGER PRIMARY KEY, name TEXT, price REAL CHECK(price > 0))`. Insert 3 valid rows and one invalid (price = 0) using `INSERT OR IGNORE`. Return `id, name, price` ordered by id.",
    category: "constraints",
    difficulty: "intermediate",
    seedSQL: "",
    expectedColumns: ["id", "name", "price"],
    expectedOutput: [
      [1, "A", 10.0],
      [2, "B", 20.0],
      [3, "C", 5.0],
    ],
    hints: [
      "CHECK(<expr>) validates on every insert/update.",
      "INSERT OR IGNORE skips the row that fails CHECK.",
      "CREATE TABLE products (... price REAL CHECK(price > 0));",
    ],
    orderMatters: true,
    expectedQuery: "CREATE TABLE products (id INTEGER PRIMARY KEY, name TEXT, price REAL CHECK(price > 0));\nINSERT INTO products VALUES (1, 'A', 10.0);\nINSERT INTO products VALUES (2, 'B', 20.0);\nINSERT INTO products VALUES (3, 'C', 5.0);\nINSERT OR IGNORE INTO products VALUES (4, 'D', 0);\nSELECT id, name, price FROM products ORDER BY id;",
  },
  {
    id: "con-04",
    title: "Composite Primary Key",
    description: "Create a link table `tagging(post_id INTEGER, tag_id INTEGER, PRIMARY KEY(post_id, tag_id))`, insert 4 rows and one duplicate (using `INSERT OR IGNORE`). Return `post_id, tag_id` ordered by both.",
    category: "constraints",
    difficulty: "intermediate",
    seedSQL: "",
    expectedColumns: ["post_id", "tag_id"],
    expectedOutput: [
      [1, 10],
      [1, 11],
      [2, 10],
      [2, 12],
    ],
    hints: [
      "Composite PK combines two columns into a unique pair.",
      "Use PRIMARY KEY(post_id, tag_id) at the table level.",
      "CREATE TABLE tagging (... PRIMARY KEY(post_id, tag_id));",
    ],
    orderMatters: true,
    expectedQuery: "CREATE TABLE tagging (post_id INTEGER, tag_id INTEGER, PRIMARY KEY(post_id, tag_id));\nINSERT INTO tagging VALUES (1, 10);\nINSERT INTO tagging VALUES (1, 11);\nINSERT INTO tagging VALUES (2, 10);\nINSERT INTO tagging VALUES (2, 12);\nINSERT OR IGNORE INTO tagging VALUES (1, 10);\nSELECT post_id, tag_id FROM tagging ORDER BY post_id, tag_id;",
  },
  {
    id: "con-05",
    title: "FOREIGN KEY with ON DELETE CASCADE",
    description: "Create `authors(id INTEGER PRIMARY KEY, name TEXT)` and `books(id INTEGER PRIMARY KEY, title TEXT, author_id INTEGER REFERENCES authors(id) ON DELETE CASCADE)`. Enable foreign keys with `PRAGMA foreign_keys = ON;`. Insert 2 authors and 3 books, then delete author 1. Return `id, title, author_id FROM books ORDER BY id` (the cascade should remove author 1's books).",
    category: "constraints",
    difficulty: "advanced",
    seedSQL: "",
    expectedColumns: ["id", "title", "author_id"],
    expectedOutput: [
      [3, "Book C", 2],
    ],
    hints: [
      "Foreign keys are OFF by default in SQLite - enable with PRAGMA foreign_keys = ON.",
      "ON DELETE CASCADE propagates deletes to child rows.",
      "REFERENCES authors(id) ON DELETE CASCADE",
    ],
    orderMatters: true,
    expectedQuery: "PRAGMA foreign_keys = ON;\nCREATE TABLE authors (id INTEGER PRIMARY KEY, name TEXT);\nCREATE TABLE books (id INTEGER PRIMARY KEY, title TEXT, author_id INTEGER REFERENCES authors(id) ON DELETE CASCADE);\nINSERT INTO authors VALUES (1, 'Ada'), (2, 'Grace');\nINSERT INTO books VALUES (1, 'Book A', 1), (2, 'Book B', 1), (3, 'Book C', 2);\nDELETE FROM authors WHERE id = 1;\nSELECT id, title, author_id FROM books ORDER BY id;",
  },
  {
    id: "con-06",
    title: "DEFAULT Values",
    description: "Create `tasks(id INTEGER PRIMARY KEY, title TEXT, status TEXT DEFAULT 'open', priority INTEGER DEFAULT 3)`. Insert 3 rows without specifying status or priority. Return all columns ordered by id.",
    category: "constraints",
    difficulty: "beginner",
    seedSQL: "",
    expectedColumns: ["id", "title", "status", "priority"],
    expectedOutput: [
      [1, "First", "open", 3],
      [2, "Second", "open", 3],
      [3, "Third", "open", 3],
    ],
    hints: [
      "DEFAULT values fill in columns you omit in INSERT.",
      "Explicitly name columns in INSERT to skip defaulted ones.",
      "CREATE TABLE tasks (... status TEXT DEFAULT 'open', priority INTEGER DEFAULT 3);",
    ],
    orderMatters: true,
    expectedQuery: "CREATE TABLE tasks (id INTEGER PRIMARY KEY, title TEXT, status TEXT DEFAULT 'open', priority INTEGER DEFAULT 3);\nINSERT INTO tasks (id, title) VALUES (1, 'First');\nINSERT INTO tasks (id, title) VALUES (2, 'Second');\nINSERT INTO tasks (id, title) VALUES (3, 'Third');\nSELECT id, title, status, priority FROM tasks ORDER BY id;",
  },
  {
    id: "con-07",
    title: "GENERATED Column",
    description: "Create `people(id INTEGER PRIMARY KEY, first TEXT, last TEXT, full TEXT GENERATED ALWAYS AS (first || ' ' || last) VIRTUAL)`. Insert 3 people and return `id, full FROM people ORDER BY id`.",
    category: "constraints",
    difficulty: "advanced",
    seedSQL: "",
    expectedColumns: ["id", "full"],
    expectedOutput: [
      [1, "Ada Lovelace"],
      [2, "Grace Hopper"],
      [3, "Linus Torvalds"],
    ],
    hints: [
      "GENERATED ALWAYS AS (<expr>) VIRTUAL computes on read.",
      "STORED computes on write (takes disk space). VIRTUAL computes on read.",
      "GENERATED ALWAYS AS (first || ' ' || last) VIRTUAL",
    ],
    orderMatters: true,
    expectedQuery: "CREATE TABLE people (id INTEGER PRIMARY KEY, first TEXT, last TEXT, full TEXT GENERATED ALWAYS AS (first || ' ' || last) VIRTUAL);\nINSERT INTO people (id, first, last) VALUES (1, 'Ada', 'Lovelace');\nINSERT INTO people (id, first, last) VALUES (2, 'Grace', 'Hopper');\nINSERT INTO people (id, first, last) VALUES (3, 'Linus', 'Torvalds');\nSELECT id, full FROM people ORDER BY id;",
  },
];
