import { Challenge } from "@/types/challenge";
import { EMPLOYEES_SEED, ECOMMERCE_SEED, MUSIC_SEED } from "../seed-data";

export const joinsChallenges: Challenge[] = [
  {
    id: "joins-01",
    title: "Basic INNER JOIN",
    description: "List all employees with their **department name**. Return first_name, last_name, and the department name. Use an INNER JOIN.",
    category: "joins",
    difficulty: "beginner",
    seedSQL: EMPLOYEES_SEED,
    expectedColumns: ["first_name", "last_name", "name"],
    expectedOutput: [
      ["Alice", "Johnson", "Engineering"],
      ["Bob", "Smith", "Engineering"],
      ["Carol", "Williams", "Marketing"],
      ["David", "Brown", "Sales"],
      ["Eva", "Davis", "Engineering"],
      ["Frank", "Miller", "Marketing"],
      ["Grace", "Wilson", "Sales"],
      ["Henry", "Moore", "HR"],
      ["Iris", "Taylor", "Finance"],
      ["Jack", "Anderson", "Engineering"],
      ["Karen", "Thomas", "Sales"],
      ["Leo", "Jackson", "Marketing"],
      ["Mia", "White", "Finance"],
      ["Noah", "Harris", "HR"],
      ["Olivia", "Martin", "Engineering"],
    ],
    hints: [
      "JOIN the employees table with the departments table",
      "Match on employees.department_id = departments.id",
      "SELECT e.first_name, e.last_name, d.name FROM employees e INNER JOIN departments d ON e.department_id = d.id",
    ],
    orderMatters: false,
  },
  {
    id: "joins-02",
    title: "LEFT JOIN - Find Missing Data",
    description: "List all employees and their **email**. Some employees might not have an email. Return first_name, last_name, and email. Make sure employees with NULL emails are included.",
    category: "joins",
    difficulty: "beginner",
    seedSQL: EMPLOYEES_SEED,
    expectedColumns: ["first_name", "last_name", "email"],
    expectedOutput: [
      ["Alice", "Johnson", "alice@company.com"],
      ["Bob", "Smith", "bob@company.com"],
      ["Carol", "Williams", "carol@company.com"],
      ["David", "Brown", "david@company.com"],
      ["Eva", "Davis", "eva@company.com"],
      ["Frank", "Miller", "frank@company.com"],
      ["Grace", "Wilson", "grace@company.com"],
      ["Henry", "Moore", "henry@company.com"],
      ["Iris", "Taylor", "iris@company.com"],
      ["Jack", "Anderson", "jack@company.com"],
      ["Karen", "Thomas", "karen@company.com"],
      ["Leo", "Jackson", "leo@company.com"],
      ["Mia", "White", "mia@company.com"],
      ["Noah", "Harris", "noah@company.com"],
      ["Olivia", "Martin", null],
    ],
    hints: [
      "This is actually a simple SELECT - no JOIN needed since email is in the employees table",
      "Just select the three columns from employees",
      "SELECT first_name, last_name, email FROM employees",
    ],
    orderMatters: false,
  },
  {
    id: "joins-03",
    title: "Multi-Table JOIN",
    description: "List all **order items** with the customer name and product name. Return the customer name, product name, quantity, and unit_price.",
    category: "joins",
    difficulty: "intermediate",
    seedSQL: ECOMMERCE_SEED,
    expectedColumns: ["name", "name", "quantity", "unit_price"],
    expectedOutput: [
      ["John Doe", "Laptop Pro", 1, 1299.99],
      ["John Doe", "Wireless Mouse", 1, 29.99],
      ["John Doe", "USB-C Hub", 1, 49.99],
      ["Jane Smith", "Mechanical Keyboard", 1, 89.99],
      ["Jane Smith", "Monitor 27\"", 1, 399.99],
      ["Pierre Dupont", "Wireless Mouse", 1, 29.99],
      ["John Doe", "Mechanical Keyboard", 1, 89.99],
      ["John Doe", "USB-C Hub", 1, 49.99],
      ["Maria Garcia", "Laptop Pro", 1, 1299.99],
      ["Yuki Tanaka", "Standing Desk", 1, 599.99],
      ["Yuki Tanaka", "Webcam HD", 1, 79.99],
      ["Emma Wilson", "Mechanical Keyboard", 1, 89.99],
      ["Jane Smith", "Ergonomic Chair", 1, 449.99],
      ["Liam Brown", "Notebook Set", 2, 12.99],
      ["Liam Brown", "Desk Lamp", 1, 34.99],
      ["Sofia Rossi", "Laptop Pro", 1, 1299.99],
      ["Sofia Rossi", "Ergonomic Chair", 1, 449.99],
    ],
    hints: [
      "You need to JOIN three tables: order_items, orders, customers, and products",
      "order_items connects to orders (order_id) and products (product_id), orders connects to customers (customer_id)",
      "SELECT c.name, p.name, oi.quantity, oi.unit_price FROM order_items oi JOIN orders o ON oi.order_id = o.id JOIN customers c ON o.customer_id = c.id JOIN products p ON oi.product_id = p.id",
    ],
    orderMatters: false,
  },
  {
    id: "joins-04",
    title: "Self JOIN - Employee Managers",
    description: "List employees with their **manager's name**. Return the employee's first_name, last_name, and their manager's first_name as manager_name. Only include employees who have a manager.",
    category: "joins",
    difficulty: "intermediate",
    seedSQL: EMPLOYEES_SEED,
    expectedColumns: ["first_name", "last_name", "manager_name"],
    expectedOutput: [
      ["Bob", "Smith", "Alice"],
      ["Frank", "Miller", "Carol"],
      ["Grace", "Wilson", "David"],
      ["Jack", "Anderson", "Eva"],
      ["Karen", "Thomas", "David"],
      ["Leo", "Jackson", "Carol"],
      ["Mia", "White", "Iris"],
      ["Noah", "Harris", "Henry"],
      ["Olivia", "Martin", "Alice"],
    ],
    hints: [
      "A self-join joins a table to itself",
      "Alias the employees table twice: once for employees and once for managers",
      "SELECT e.first_name, e.last_name, m.first_name AS manager_name FROM employees e INNER JOIN employees m ON e.manager_id = m.id",
    ],
    orderMatters: false,
  },
  {
    id: "joins-05",
    title: "JOIN with Aggregation",
    description: "Show each department name and the **number of employees** in it. Return department name and employee_count, ordered by count descending.",
    category: "joins",
    difficulty: "intermediate",
    seedSQL: EMPLOYEES_SEED,
    expectedColumns: ["name", "employee_count"],
    expectedOutput: [
      ["Engineering", 5],
      ["Marketing", 3],
      ["Sales", 3],
      ["Finance", 2],
      ["HR", 2],
    ],
    hints: [
      "JOIN departments with employees, then GROUP BY department",
      "Use COUNT() to count employees per department",
      "SELECT d.name, COUNT(e.id) AS employee_count FROM departments d JOIN employees e ON d.id = e.department_id GROUP BY d.name ORDER BY employee_count DESC",
    ],
    orderMatters: true,
  },
  {
    id: "joins-06",
    title: "LEFT JOIN - All Departments",
    description: "Show **all departments** with their employee count, including departments with zero employees. Return department name and employee_count.",
    category: "joins",
    difficulty: "intermediate",
    seedSQL: EMPLOYEES_SEED,
    expectedColumns: ["name", "employee_count"],
    expectedOutput: [
      ["Engineering", 5],
      ["Finance", 2],
      ["HR", 2],
      ["Marketing", 3],
      ["Sales", 3],
    ],
    hints: [
      "Use LEFT JOIN so departments without employees still appear",
      "COUNT(e.id) will be 0 for departments with no matching employees",
      "SELECT d.name, COUNT(e.id) AS employee_count FROM departments d LEFT JOIN employees e ON d.id = e.department_id GROUP BY d.name",
    ],
    orderMatters: false,
  },
  {
    id: "joins-07",
    title: "JOIN with Track and Album Data",
    description: "List all tracks with their **album title** and **artist name**. Return track title, album title, and artist name.",
    category: "joins",
    difficulty: "intermediate",
    seedSQL: MUSIC_SEED,
    expectedColumns: ["title", "title", "name"],
    expectedOutput: [
      ["Sunset", "Endless Summer", "The Midnight"],
      ["Endless Summer", "Endless Summer", "The Midnight"],
      ["Vampires", "Nocturnal", "The Midnight"],
      ["Crystalline", "Nocturnal", "The Midnight"],
      ["Get Lucky", "Random Access Memories", "Daft Punk"],
      ["Instant Crush", "Random Access Memories", "Daft Punk"],
      ["One More Time", "Discovery", "Daft Punk"],
      ["Digital Love", "Discovery", "Daft Punk"],
      ["Do I Wanna Know?", "AM", "Arctic Monkeys"],
      ["R U Mine?", "AM", "Arctic Monkeys"],
      ["Four Out of Five", "Tranquility Base Hotel", "Arctic Monkeys"],
      ["Let It Happen", "Currents", "Tame Impala"],
      ["The Less I Know", "Currents", "Tame Impala"],
      ["Lost In Yesterday", "The Slow Rush", "Tame Impala"],
      ["Maria También", "Con Todo El Mundo", "Khruangbin"],
      ["Time (You and I)", "Mordechai", "Khruangbin"],
    ],
    hints: [
      "Join tracks → albums → artists",
      "tracks.album_id = albums.id, albums.artist_id = artists.id",
      "SELECT t.title, al.title, ar.name FROM tracks t JOIN albums al ON t.album_id = al.id JOIN artists ar ON al.artist_id = ar.id",
    ],
    orderMatters: false,
  },
  {
    id: "joins-08",
    title: "CROSS JOIN",
    description: "Generate all possible combinations of **department names** and **project names**. Return department name and project name. (Hint: you need a CROSS JOIN)",
    category: "joins",
    difficulty: "intermediate",
    seedSQL: EMPLOYEES_SEED,
    expectedColumns: ["name", "name"],
    expectedOutput: [
      ["Engineering", "Website Redesign"], ["Engineering", "Mobile App"], ["Engineering", "Q1 Campaign"], ["Engineering", "Sales Portal"], ["Engineering", "Employee Portal"],
      ["Marketing", "Website Redesign"], ["Marketing", "Mobile App"], ["Marketing", "Q1 Campaign"], ["Marketing", "Sales Portal"], ["Marketing", "Employee Portal"],
      ["Sales", "Website Redesign"], ["Sales", "Mobile App"], ["Sales", "Q1 Campaign"], ["Sales", "Sales Portal"], ["Sales", "Employee Portal"],
      ["HR", "Website Redesign"], ["HR", "Mobile App"], ["HR", "Q1 Campaign"], ["HR", "Sales Portal"], ["HR", "Employee Portal"],
      ["Finance", "Website Redesign"], ["Finance", "Mobile App"], ["Finance", "Q1 Campaign"], ["Finance", "Sales Portal"], ["Finance", "Employee Portal"],
    ],
    hints: [
      "A CROSS JOIN produces the Cartesian product of two tables",
      "No ON clause needed with CROSS JOIN",
      "SELECT d.name, p.name FROM departments d CROSS JOIN projects p",
    ],
    orderMatters: false,
  },
];
